// Auto-generated from docs/learning/*.md — do not edit manually.
// Run: bun scripts/generate-learning-contribution.ts
import type { RuntimeLearningContribution } from "@vivy1024/novelfork-core/plugins";

const t = (zh: string) => ({ en: zh, "zh-CN": zh });

export const GENERATED_LEARNING_CONTRIBUTION: RuntimeLearningContribution = {
  categories: [
    { id: "novelfork-writing", label: t("NovelFork 写作"), description: t("创建作品、书籍管理、写作管线与叙述者协作。") },
    { id: "novelfork-context", label: t("NovelFork 设定与记忆"), description: t("经纬/Lore、叙事记忆、写作分析工具与 Agent 管线。") },
    { id: "novelfork-settings", label: t("NovelFork 设置与管理"), description: t("AI 供应商、套路、代理、安全、终端与运行环境配置。") },
    { id: "novelfork-advanced", label: t("NovelFork 进阶"), description: t("子代理、模型配置、调试、写作规范与平台合规。") },
  ],
  docs: [
    {
      id: "overview",
      category: "novelfork-writing",
      tags: ["入门","概览","快速上手"],
      title: t("一页理解 NovelFork"),
      summary: t("网文小说 AI 辅助创作工作台，对话驱动、本地运行、数据不出机"),
      sections: [
        { title: t("它是什么"), body: t("NovelFork 是本地运行的网文创作工作台。你通过对话告诉 AI 想写什么，AI 帮你规划、写作、审校。你掌控方向和设定，AI 负责产出文字。") },
        { title: t("界面布局"), body: t("三栏结构：\n\n- **左栏**：资源树 — 书籍、章节、经纬资料、伏笔\n- **中间**：画布 — 阅读和编辑章节内容\n- **右侧**：叙述者对话 — 你和 AI 交流的主入口") },
        { title: t("5 分钟上手"), body: t("1. **配置模型**：设置 → 供应商 → 添加 API Key 和地址\n2. **创建作品**：左栏「新建作品」→ 填书名、选题材\n3. **开始写作**：右侧对话框告诉叙述者你想写什么\n4. **审阅结果**：AI 生成的正式章节结果出现在画布中，可继续编辑") },
        { title: t("核心概念"), body: t("| 概念 | 一句话解释 |\n|------|-----------|\n| 叙述者 | 右侧的 AI 对话助手，你的写作搭档（每本书自带，不可删除） |\n| 经纬 | 世界观/角色/设定的结构化存储，AI 写作时自动注入 |\n| 叙事记忆 | 正文产生的动态事实流（角色状态、关系、伏笔、事件），与经纬分工 |\n| 写作技能 (Writing Skills) | 可组合的写作规则与合规检查，取代旧 Preset/Beat |\n| 写作管线 | scene.spec → pipeline.write → 对抗审查 → S1–S4 门禁 |\n| 套路 | Agent 行为规则集：命令/工具/权限/技能/MCP/Hooks |\n| 工具面板 | 每日进度/质量趋势/文风漂移/伏笔看板/角色弧线/合规检查 |") },
      ],
      workflow: [],
      bestPractices: [t("**先聊再写**：先和叙述者讨论想法、人物、冲突，再动笔"), t("**经纬越全越好**：AI 能看到的设定越多，生成质量越高"), t("**启用写作技能让 AI 守规矩**：在写作配置中按需组合 Style / Plot / Character 类 Skills"), t("**首次引导向导**：首次进入设置时会弹出 6 步引导（供应商→模型→网络），跟随完成即可上手")],
      pitfalls: [t("叙述者无响应 → 设置页检查供应商状态，确认 API Key 有效"), t("AI 写的和设定矛盾 → 检查经纬条目是否已创建并开启 AI 参与"), t("生成太慢 → 经纬条目过多撑爆上下文，精简不相关条目"), t("预设没生效 → 让叙述者帮你设置：\"帮我选择适合这本书的预设\"")],
      agentHints: [t("数据目录：`~/.novelfork/`（SQLite + 文件系统）"), t("前端路由基础路径：`/next`"), t("叙述者对话路由：`/next/narrators/:sessionId`"), t("作品工作台路由：`/next/books/:bookId`"), t("设置路由：`/next/settings`"), t("套路路由：`/next/routines`"), t("学习中心路由：`/next/learn`")],
      actions: [
      { label: t("前往"), description: t("/next"), href: "/next" },
      ],
    },
    {
      id: "book-management",
      category: "novelfork-writing",
      tags: ["作品","章节","资源树","新书向导"],
      title: t("作品与章节管理"),
      summary: t("创建作品、管理章节、资源树结构、新书引导向导"),
      sections: [
        { title: t("核心概念"), body: t("**资源树**（左栏）展示当前作品的全部资源：\n\n```\n📖 我的作品\n├── 📁 章节\n│   ├── 第一章 初入江湖\n│   └── 第二章 暗流涌动\n├── 📁 经纬资料\n│   ├── 故事经纬\n│   ├── 卷大纲\n│   └── 书籍规则\n└── 📁 伏笔\n    └── 待处理伏笔\n```\n\n**新书引导向导**（NewBookGuide）：创建作品时 11 题三模式——预设选择 / 自定义填写 / 跳过随机。完成后自动生成初始经纬条目。\n\n**章节状态**：写作中 → 正式章节。正式章节可继续编辑。") },
      ],
      workflow: [],
      bestPractices: [t("新书向导不要全部跳过，至少填核心前提和主角，AI 才有方向"), t("章节命名保持统一格式（如\"第X章 标题\"），方便导出和排序"), t("一本书对应一个主叙述者会话，避免上下文分散")],
      pitfalls: [t("**新书向导生成的经纬为空** → 向导全部跳过时生成随机内容，质量不高，建议至少填 3 题"), t("**章节顺序错乱** → 章节按创建时间排序，可在资源树中拖拽调整"), t("**删除章节不可恢复** → 删除前先打 Checkpoint 快照")],
      agentHints: [t("作品 CRUD 通过 `/api/books` REST 接口"), t("章节通过 `pipeline.write` 生成正式章节结果并入库"), t("资源树数据通过 `/api/books/:bookId/resources` 获取"), t("新书向导完成后触发经纬初始化流程，调用 AI 填充 story_bible")],
      actions: [
      { label: t("前往"), description: t("/next/books"), href: "/next/books" },
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "ai-writing",
      category: "novelfork-writing",
      tags: ["AI写作","正式章节","续写","扩写","变体","WritingSkills","节奏预算"],
      title: t("AI 写作功能"),
      summary: t("选段写作、多版本变体、正式章节结果流程、Writing Skills 与节奏预算"),
      sections: [
        { title: t("核心概念"), body: t("**选段写作**：选中文本后执行续写（从光标处继续）、扩写（展开细节）、补写（两段之间插入过渡）。结果进入正式章节结果或预览边界，不静默覆盖正文。\n\n**多版本变体**：同一段落生成 2-4 个不同风格版本，并排对比后选择最满意的。\n\n**正式章节结果**：AI 生成后的稳定正文层。AI 生成 → 正式章节 artifact/画布 → 你审阅和继续编辑。AI 不创建 candidate/draft 主对象。\n\n**写作预设**：已由 Writing Skills 统一取代，不再单独维护预设条目。\n\n**Writing Skills**：不是独立注入概念，就是一个技能市场加落盘。启用后物化到作品目录 `.novelfork/skills/<slug>/SKILL.md`，Runtime 自动扫描，叙述者按普通 Skill 读取。写章前由同一 Runtime 会话先调用 Skill 工具读取相关技能；写后按技能规则硬校验（`writing-skills.check_compliance`）。\n\n**节拍模板**：已由 Writing Skills 取代；旧数据可用 `writing-skills.import_legacy` 迁移。\n\n**上下文组装**：系统自动按优先级注入——经纬条目 → 前文摘要 → 驾驶舱快照 → PGI 回答 → Scene Spec 蓝图。Writing Skills 不走这条通道，由叙述者自己读磁盘上的 SKILL.md。") },
        { title: t("写作工具一览"), body: t("| 工具 | 适用场景 | 说明 |\n|------|---------|------|\n| `pipeline.write` | 写下一章 | 校验并保存 Runtime Agent 提交的正文：写前门→落盘→章后结算 |\n| `chapter.audit` | 定位整章问题 | 纯规则审计，不调模型 |\n| `rewrite.apply` | 写回改写结果 | 按行范围替换或插入（改写文本由 Runtime Agent 提交） |\n| `writing-skills.check_compliance` | 按启用技能审正文 | 规则校验，硬性违规会阻断保存 |\n| `writing-skills.write` | 创建/启用文风技能 | 文风以 Writing Skill 落盘，写前由 Runtime Skill 机制读取 |\n\n去 AI 味不再有独立工具或模式：由 story-deslop Writing Skill 承担。内部调模型的选段改写、文风导入与大纲建议等旧工具已下线，相关结果由同一 Runtime Agent 直接生成后经 `rewrite.apply` / `writing-skills.write` 落盘。") },
      ],
      workflow: [],
      bestPractices: [t("用\"生成下一章\"而非\"续写片段\"，前者走完整 PGI + SceneSpec + pipeline 流程，质量更高"), t("不确定方向时先生成变体对比，再决定采纳哪个"), t("一部作品尽量固定一套 Writing Skills，避免前后文风不一致"), t("让叙述者帮你选技能：\"帮我选择适合玄幻的写作技能\"（`writing-skills.recommend`）")],
      pitfalls: [t("**生成内容重复前文** → 上下文中前文摘要太长，手动精简"), t("**章节结果字数不达标** → 先看 `scene.spec` 的情节点预算是否合规；预算合计低于章目标时 `pipeline.write` 会以 `beat-budget-invalid` 拒绝执行，需回去把密点拆细"), t("**风格漂移** → Writing Skills 中途切换导致，固定一套技能"), t("**启用了技能但看起来没生效** → 确认当前会话先用 Skill 工具读取了 `.novelfork/skills/<slug>/SKILL.md`（写前 preflight 会提示相关技能未加载）；违规项会出现在 `publishHint.warnings`"), t("**提示正文已保存但结算失败** → 返回 `settlementError` 时对该章执行 `memory.settle_range` 补结算")],
      agentHints: [t("生成结果通过 `pipeline.write` 进入正式章节结果；禁止创建 candidate/draft 主对象或绕过确认静默覆盖用户正文"), t("上下文组装顺序固定：经纬 → 前文摘要 → 驾驶舱快照 → PGI → SceneSpec"), t("Writing Skills 落盘在作品的 `.novelfork/skills/`，写章前必须先用 Skill 工具读取相关技能；同一会话的 Skill 调用记录是生效证据"), t("变体生成时每个变体独立走完整管线，共享上下文但 temperature 不同"), t("文风以 Writing Skill 落盘并启用（`writing-skills.write`），写前由 Runtime Skill 机制加载")],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "guided-generation",
      category: "novelfork-writing",
      tags: ["PGI","引导式生成","追问","AskUserQuestion","scene.spec"],
      title: t("引导式生成"),
      summary: t("PGI 追问机制、AskUserQuestion 交互、scene.spec 蓝图批准"),
      sections: [
        { title: t("核心概念"), body: t("**PGI（Pre-Generation Interview）**：生成前追问。AI 在动笔前先问 1-3 个精准问题，明确你对这章的期望——情绪基调、关键事件、字数要求等。\n\n**pgi.ask**：PGI 单一工具。一次调用完成：基于驾驶舱、静态 Lore 与动态叙事记忆判断是否需要追问 → 返回可供 AskUserQuestion 展示的问题卡。\n\n**AskUserQuestion**：AI 向用户展示问题卡片的工具。PGI 生成的追问通过此工具呈现为选择题/文本输入，用户回答后 Agent 继续执行。整个写作流程只调用一次。\n\n**scene.spec**：结构化写作蓝图生成工具。包含角色、地点、冲突、情绪、结果等约束，是 `pipeline.write` 的硬前置条件——也是你动笔前最后的方向把关点。") },
        { title: t("完整流程（v3.0.0）"), body: t("```\n用户请求（写下一章）\n  → cockpit.snapshot（了解进度/伏笔/章节结果状态）\n  → lore.read(scope=brief)（读静态设定核心包）\n  → memory.read(purpose=write)（读动态叙事记忆）\n  → pgi.ask（生成追问）\n  → AskUserQuestion（展示给用户，整个流程只一次）\n  → 用户回答\n  → scene.spec（生成结构化蓝图）\n  → lore.read(scope=category) + memory.read（按蓝图补读静态设定与动态上下文）\n  → pipeline.write（执行写作，传入 sceneSpec）\n  → 正式章节结果（以 artifact 打开审阅）\n```\n\n> 注：v1.7.0 之前存在独立的 `guided.enter / answer_question / exit` 与 `questionnaire.*` 工具层做\"计划批准\"，现已折叠——计划确认由 AskUserQuestion + scene.spec 承担，不再有单独的 guided 工具。") },
        { title: t("追问触发条件"), body: t("PGI 基于启发式规则自动生成追问：\n\n| 启发式 | 触发条件 | 追问内容 |\n|--------|---------|---------|\n| `conflict-escalating` | 检测到升级中的矛盾 | 本章是否继续升级或推向高潮 |\n| `foreshadow-due` | 检测到临近回收的伏笔 | 本章是否兑现或延后 |\n| 通用 | 信息不足时 | 确认写作方向、POV、情绪落点 |\n\n无问题时设置 `skippedReason=no-questions` 并继续后续流程。") },
      ],
      workflow: [],
      bestPractices: [t("PGI 回答越具体，生成质量越高。\"这章要写主角被背叛后的愤怒，3000字，以独白结尾\"比\"写下一章\"好得多"), t("不确定时可以跳过 PGI（AI 会用 `skippedReason` 继续），但质量会下降"), t("scene.spec 是你最后的方向把关机会，认真审阅")],
      pitfalls: [t("**PGI 问题太多** → AI 判断信息不足时会多问，在经纬中补充设定可减少追问"), t("**跳过 PGI 后质量差** → 正常现象，PGI 是质量保障的关键环节")],
      agentHints: [t("PGI 用单一工具 `pgi.ask`（已合并旧三步）"), t("不存在独立的 guided 工具层；计划确认 = AskUserQuestion + scene.spec"), t("整章生成走 `pipeline.write`（传入 sceneSpec），产出正式章节结果"), t("PGI 无问题时设置 `skippedReason=no-questions` 并继续"), t("AskUserQuestion 通过工具触发，前端渲染为选择卡片")],
      actions: [
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "narrator-conversation",
      category: "novelfork-writing",
      tags: ["叙述者","对话","确认门","工具调用","会话"],
      title: t("叙述者对话"),
      summary: t("有状态的 Agent 会话界面，自然语言驱动一切创作操作"),
      sections: [
        { title: t("核心概念"), body: t("叙述者不是聊天机器人。它是有状态的 Agent：能调用工具、修改资源、记住上下文。\n\n**每本书有多个叙述者**：写书、审校、伏笔、章末钩子、大纲与经纬——各司其职。\n\n**确认门**：AI 写入正式资源前暂停等待你批准。风险分级：read（绿）/ write（黄）/ delete（红）。\"始终允许此类操作\"可永久放行同类调用。\n\n**状态栏**：顶部实时显示空闲/工作中/等待输入 + 上下文使用率 + 当前模型 + 权限模式 + 超时配置（默认 120 秒，可在状态栏直接修改）。\n\n**Slash 命令**：输入框中 `/` 触发——`/help` `/model` `/permission` `/compact` `/fork`。") },
        { title: t("右键菜单操作"), body: t("对话消息支持右键菜单，各操作对应独立 API：\n\n- **回退到此处**（Rollback）— 将对话回退到选中消息，后续消息被丢弃。调用 `rollback` API。\n- **编辑并重新生成**（Edit & Regenerate）— 修改你之前发送的消息内容，AI 基于修改后的内容重新回复。调用 `edit-and-regenerate` API。\n- **分叉** — 从此处创建新分支探索不同方向\n- **删除** — 删除单条消息\n\n> 注意：\"清空上下文\"（`/compact`）和\"回退到此处\"是不同操作。前者压缩历史保留摘要，后者直接丢弃后续消息回到指定时间点。") },
      ],
      workflow: [],
      bestPractices: [t("Context Ring 接近满时生成质量下降，主动 `/compact`"), t("不要开 auto-approve 除非完全信任当前流程"), t("善用消息多选（Ctrl+Click / Shift 范围选）批量操作")],
      pitfalls: [t("**AI 回复越来越短** → 上下文快满了，执行 `/compact`"), t("**确认门频繁弹出** → 权限模式为 ask-always，可切换到 auto-approve（需谨慎）"), t("**模型切换后风格变化** → 在经纬中明确文风要求可缓解"), t("**操作超时** → 状态栏可调整超时时间，默认 120 秒")],
      agentHints: [t("叙述者工具集：Read/Write/Edit/Bash/Grep/Glob + 小说专属工具（cockpit/lore/memory/pgi/scene.spec/pipeline.write 等）"), t("确认门触发条件：写入正式章节、修改经纬、删除资源、执行修订"), t("权限模式：ask-always（每次确认）/ auto-approve（自动批准低风险）"), t("消息操作：右键菜单支持回退（rollback API）/编辑重生成（edit-and-regenerate API）/分叉/删除"), t("清空上下文 ≠ 回退：compact 保留摘要，rollback 丢弃后续消息"), t("状态栏超时配置：用户可自定义工具执行超时（默认 120 秒）"), t("WebSocket 自动重连 + 断点续传，刷新后自动恢复会话"), t("Bash 工具实时输出流：stdout 实时推送到前端")],
      actions: [
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "story-jingwei",
      category: "novelfork-context",
      tags: ["经纬","Lore","世界观","设定","叙事记忆"],
      title: t("故事经纬"),
      summary: t("静态 Lore 设定库，管理作者确认的世界规则、人物、地点与术语，并与叙事记忆分工"),
      sections: [
        { title: t("核心概念"), body: t("**经纬（Jingwei / Lore）**：二级结构——分区 → 条目。适合保存作者确认的静态材料：人物、地点、势力、世界规则、物品、术语、作者备注等。\n\n**叙事记忆（Narrative Memory）**：保存动态叙事事实：人物关系变化、时间线推进、角色弧线、伏笔埋设/触发/兑现、章节后抽取事实、召回 diagnostics。\n\n二者分工：\n\n| 类型 | 放在哪里 | 工具 |\n|------|----------|------|\n| 世界规则、人物固定设定、地点、势力、术语 | 经纬 / Lore | `lore.read` / `lore.write` |\n| 章节后发生的事件、关系变化、伏笔状态、时间线推进 | 叙事记忆 | `memory.read` / `memory.events` / `memory.graph` |\n| 作者临时参考、素材摘录 | 经纬参考类条目 | `lore.read(scope=search)` |") },
        { title: t("在资源树中的展示"), body: t("```\n📁 经纬资料 / Lore\n├── 人物设定\n├── 地点与势力\n├── 世界规则\n├── 术语与物品\n└── 作者备注\n\n📁 叙事记忆\n├── 动态事实\n├── 时间线\n├── 伏笔网络\n├── 角色弧线\n└── 关系图 / 矛盾地图\n```\n\n> v3.0.0 起，原经纬中关系、伏笔、时间线、核心矛盾等动态条目已迁移为 `narrative_fact`，不再作为静态经纬分类维护。") },
        { title: t("AI 上下文参与"), body: t("AI 写作前会按链路读取：\n\n```\ncockpit.snapshot → lore.read(scope=brief) → memory.read(purpose=write)\n  → pgi.ask → scene.spec\n  → lore.read(scope=category) + memory.read → pipeline.write\n```\n\n- `lore.read(scope=brief)`：读取静态设定核心摘要。\n- `lore.read(scope=category/search)`：按 scene.spec 中角色、地点、规则补读精确信息。\n- `memory.read(purpose=write)`：读取动态 ContextCard（时间线、伏笔、状态、事实等）。") },
        { title: t("Canon / Rules 写入门禁"), body: t("为了防止 AI 长对话中污染正史，v3.0.0 对静态 Lore 写入加了门禁：\n\n- `lore.read` 默认排除 `archived` / `draft` / `needs-review` 条目。\n- `lore.write` 写 `canon` 或 `rules` 必须提供 `reason`、`source`、`evidence`。\n- 动态事实不得直接写进 Lore；应通过 `memory.events` 创建 pending NarrativeEvents，由用户批准。\n- `jingwei.read/write` 仍保留为兼容别名，但新流程优先使用 `lore.*`。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [t("**把角色关系网放进经纬** → 关系会随剧情变化，应进入 Narrative Memory。"), t("**把时间线当静态设定写** → 时间线推进属于动态记忆，应走 `memory.events`。"), t("**AI 写出未确认设定** → 检查是否把 draft/needs-review 条目误参与 AI，或让 AI 绕过 evidence 门禁。"), t("**经纬越写越臃肿** → 只保留长期稳定的静态事实，章节摘要与事件交给叙事记忆。")],
      agentHints: [t("静态设定优先用 `lore.read(scope=brief/category/search)`。"), t("动态上下文优先用 `memory.read(purpose=write|audit|revise)`。"), t("写完章节后的摘要、角色变化、伏笔推进默认生成 `memory.events` pending 事件。"), t("不要把 `memory.events` 可表达的动态事实直接写进 `lore.write(canon/rules)`。")],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "settings-and-routines",
      category: "novelfork-context",
      tags: ["设置","供应商","套路","MCP","模型","Hooks"],
      title: t("设置与套路"),
      summary: t("配置 AI 供应商、模型路由，用套路系统定义 Agent 行为边界"),
      sections: [
        { title: t("核心概念"), body: t("**供应商**：AI 模型的 API 连接配置（Key + Endpoint + 可用模型列表）。支持 OpenAI / Anthropic / 自定义端点。\n\n**模型聚合**：多供应商的同名模型合并为一个逻辑模型，按策略路由（priority / round-robin / random）。\n\n**套路（Routines）**：Agent 行为规则集。全局套路对所有作品生效，项目套路覆盖全局。\n\n**MCP 扩展**：连接外部 MCP Server 为 Agent 注入额外工具能力。") },
        { title: t("套路系统 10 大维度"), body: t("套路页面包含 10 个配置维度：\n\n| 标签 | 功能 | 说明 |\n|------|------|------|\n| **Commands** | 自定义斜杠命令 | 定义 `/命令名` → prompt 模板，Composer 中 `/` 触发补全 |\n| **Tools** | 可选工具开关 | 控制哪些工具对 Agent 可见，支持 `/load` 等价入口 |\n| **Permissions** | 工具权限规则 | 每个工具的权限行为：allow / deny / ask，支持 pattern 匹配 |\n| **Global Skills** | 全局技能 | 全局生效的技能指令，支持展开文件树与在线预览 SKILL.md 源码 |\n| **Project Skills** | 项目技能 | 项目级技能，自动发现作品 `.novelfork/skills/` 文件，随作品迁移且不影响全局 |\n| **SubAgents** | 子代理定义 | 自定义子代理类型：名称、systemPrompt、工具权限 |\n| **Global Prompts** | 全局提示词 | 注入所有叙述者的 system prompt 中 |\n| **System Prompts** | 系统提示词 | 更底层的系统提示注入 |\n| **MCP Tools** | MCP 工具 | 外部 MCP Server 暴露的工具，支持审批 |\n| **Hooks** | 钩子 | shell/webhook/llm 三种类型，在工具调用前后触发 |") },
        { title: t("v3.3.2：Writing Skill 文件自动发现"), body: t("1. **Skill 文件树在线浏览**：在“全局技能”与“作品技能”卡片上，点击“查看文件”可展开 Skill 内包含的所有文件列表（如 `SKILL.md`、`templates/*.md`），点击文件名可直接在弹窗中实时预览源码与 Markdown 格式。\n2. **作品 Skill 自动发现 (`.novelfork/skills/`)**：Runtime、写作 preflight 和工具解析会自动扫描作品根目录的 `.novelfork/skills/<slug>/`，读取其中的 `SKILL.md` 及关联附件；不再通过 `book.json` 的启用列表判断生效状态。\n3. **面板增量同步**：写作配置面板的添加/删除/刷新只操作指定项目 Skill 文件，不会覆盖或删除其它手动放入 `.novelfork/skills/` 的技能。\n4. **设置项脏检测 (Dirty Bar)**：供应商及模型设置采用与 NarraFork 原生一致的脏检测模式——修改配置后底部出现固定浮条提示未保存，点击“保存变更”批量提交。\n5. **首次启动引导向导 (SetupWizard)**：首次进入设置时自动弹出 6 步引导（环境依赖检测 → AI 供应商校验 → 基础模型与摘要模型配置 → 网络监听模式 → 完成）。") },
        { title: t("Hooks 钩子系统"), body: t("三种触发时机：\n\n| 钩子类型 | 触发时机 | 典型用途 |\n|---------|---------|---------|\n| PreToolUse | 工具执行前 | 参数校验、审计日志 |\n| PostToolUse | 工具执行后 | 结果后处理、通知 |\n| TurnComplete | 对话轮次结束后 | 自动备份、统计 |\n\n三种执行方式：\n\n| 类型 | 说明 |\n|------|------|\n| `shell` | 执行 shell 命令 |\n| `webhook` | 发送 HTTP 请求 |\n| `llm` | 调用 LLM 进行判断 |") },
        { title: t("Workflow Recipes"), body: t("可配置的工作流程配方，定义命令的执行链：\n\n```json\n{\n  \"commandId\": \"/novel:write-next\",\n  \"steps\": [\"cockpit.snapshot\", \"pgi.ask\", \"AskUserQuestion\", \"scene.spec\", \"pipeline.write\"]\n}\n```") },
      ],
      workflow: [],
      bestPractices: [t("先配好供应商再做其他事，没有可用模型一切功能不可用"), t("全局套路放通用规则，项目套路放题材定制"), t("模型聚合用 priority 策略时把最稳定的供应商排第一"), t("权限建议从 ask 开始，熟悉后再切 allow"), t("自定义子代理的 systemPrompt 要明确限定它的职责边界")],
      pitfalls: [t("**模型列表为空** → API Key 过期或 Base URL 错误，用\"测试连接\"验证"), t("**命令不生效** → 检查套路命令 Tab 是否被禁用；项目套路会覆盖全局"), t("**MCP 工具超时** → MCP 服务器未启动或网络不通"), t("**聚合路由不切换** → 只有请求失败才触发 fallback"), t("**Hooks 不执行** → 检查 enabled 状态和触发事件匹配")],
      agentHints: [t("供应商配置存储在 settings store，通过 `useSettingsStore` 读取"), t("套路合并逻辑：全局 + 项目，同名项目优先；提示词拼接（全局在前）"), t("会话创建时套路注入 sessionConfig：commands / tools / permissionMode / skills / subAgents / systemPrompt"), t("自定义斜杠命令：定义 `/命令名` → prompt 模板，Composer 中 `/` 触发补全"), t("全局提示词注入到所有叙述者的 system prompt 中"), t("被禁用的 runtime command IDs 存储在 `disabledCommands` 字段"), t("Workflow Recipes 定义命令的工具调用执行链")],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      { label: t("前往"), description: t("/next/routines"), href: "/next/routines" },
      ],
    },
    {
      id: "writing-tools",
      category: "novelfork-context",
      tags: ["写作工具","AI味","健康度","文风","合规","导出","快照"],
      title: t("写作分析工具"),
      summary: t("AI 味检测、章节健康度、文风漂移、角色弧线、合规导出、快照回滚"),
      sections: [
        { title: t("核心概念"), body: t("工具分两类：\n- **章节级**：AI 味检测、段落节奏、对话比例——作用于单章\n- **全书级**：健康度仪表盘、文风漂移、角色弧线、连续性审计——作用于整本书\n\n| 工具 | 作用 |\n|------|------|\n| AI 味检测 | 12 规则本地扫描，标注 AI 痕迹段落 |\n| 章节健康度 | 节奏/对话/句长直方图 |\n| 文风漂移检测 | 对比各章与目标文风的偏离 |\n| 角色弧线追踪 | 检查角色成长是否连贯 |\n| 连续性审计 | 检测剧情矛盾、人设冲突、时间线错误 |\n| 平台合规检查 | 敏感词扫描 |\n| 导出 | TXT / Word / ePub |\n| Checkpoint | 资源快照与回滚 |") },
      ],
      workflow: [],
      bestPractices: [t("AI 味检测在初稿完成后立即跑，越早修正越省力"), t("文风检测前先在经纬中声明目标文风，否则无基准可比"), t("合规检查在每次导出前必跑"), t("大改前打 Checkpoint 快照，改坏了一键回滚")],
      pitfalls: [t("**AI 味检测结果为空** → 章节内容不足 500 字，本地规则需要最低文本量"), t("**文风检测不准** → 未在经纬中设置目标文风描述"), t("**导出格式异常** → 章节标题格式不统一，先跑合规检查")],
      agentHints: [t("AI 味检测组件：`AiTasteReport`，12 条本地规则优先执行"), t("健康度组件：`ChapterHealthCard`（章节级）+ `BookHealthSummary`（全书级）"), t("文风漂移：`StyleDriftPanel`，对比当前章与目标文风的向量距离"), t("角色弧线：`CharacterArcsPanel`，从经纬角色设定 + 章节内容提取 arc beats"), t("合规导出：`CompliancePanel` 扫描 → `ExportPanel` 输出"), t("Word 导出：零依赖 .docx 生成，直接构建 OpenXML 包"), t("Checkpoint：`CheckpointPanel`，快照存储在 SQLite，回滚恢复全部资源状态")],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "agent-pipeline",
      category: "novelfork-context",
      tags: ["Agent","Pipeline","工具层","写作","正式章节","叙事记忆","写前预检"],
      title: t("Agent 写作管线"),
      summary: t("write.preflight 硬门、scene.spec 蓝图、pipeline.write 正文与章后结算的完整工具链"),
      sections: [
        { title: t("权威链路"), body: t("```\n用户请求写下一章\n  → write.preflight            ← 硬门：不通过就停下，不许先写\n  →（缺上下文时）memory.settle_range / outline.volume\n  → pgi.ask（意图仍模糊时）\n  → scene.spec(userDirectives = resolvedDirective)\n  → pipeline.write\n  → 正式章节结果 + 章后自动结算\n  →（发布前）publish.check\n```\n\n**核心原则**：\n\n- **写前硬门不可跳过**。`write.preflight` 组装最小上下文包并做机器校验；`ok=false` 时必须停下报告缺什么，不能凭想象补前情。\n- Agent 本身就是调度器；工具链顺序由系统提示词约束。\n- 写作结果进入正式章节结果，不创建 candidate/draft 主对象。\n- 静态设定从 `lore.*` 读取；动态事实从 `memory.*` 读取。\n- 写后变化先进入 pending 队列，由用户确认，避免 AI 自动污染 canon。") },
        { title: t("`write.preflight` 拦什么"), body: t("| 阻断项 | 含义 | 解法 |\n|--------|------|------|\n| `missing-directive` | 没有本章目标，且焦点也推不出默认句 | 补一句本章要发生什么 |\n| `empty-recent-progress` | 已有章节进度，但近章摘要/记忆为空 | `memory.settle_range` 回填；废稿先 `chapter.discard_range` |\n| `high-risk-pending` | 存在高风险待确认事件 | 先在经纬工作区「进度」分区确认或驳回 |\n| `skills-not-acknowledged` | 本书已启用 Writing Skills，但当前会话未先加载相关技能（提示项） | 先用 Skill 工具读取 `.novelfork/skills/<slug>/SKILL.md` 再写 |\n| `book-not-found` | 书籍绑定无效 | 检查 bookId |\n\n告警（不阻断，但要看）：`short-directive`、`focus-default-only`、`empty-chapter-summary`、`hooks-overdue`、`style-disabled`、`volume-focus-missing`、`platform-target-mismatch`。\n\n每条拦截和告警都带 `explanation` 三段式（发生了什么 / 为什么要看 / 建议怎么做）。**前端与叙述者不得按 code 自造文案**，直接转述 explanation。\n\n`needsUserConfirm=true` 表示只有焦点默认目标、没有用户明确指示：需要用户确认，或显式传 `acceptFocusDefault=true`。") },
        { title: t("可用写作工具"), body: t("| 工具 | 用途 | 风险等级 |\n|------|------|---------|\n| `write.preflight` | 写前硬门：组装最小上下文包并拦截缺失输入 | read |\n| `cockpit.snapshot` | 获取当前书籍、章节和资源状态快照 | read |\n| `lore.read` | 读取作者确认的静态 Lore（brief/category/search） | read |\n| `memory.read` | 读取动态叙事记忆 ContextCard | read |\n| `pgi.ask` | 生成写前追问，补齐本章意图 | read |\n| `scene.spec` | 校验 Runtime Agent 提交的结构化写作蓝图 | read |\n| `pipeline.write` | 校验并保存 Runtime Agent 提交的正文：写前门→落盘→章后结算 | draft-write |\n| `memory.events` | 写后整理章节摘要、关系变化、伏笔推进为 pending 事件 | draft-write |\n| `memory.settle_range` | 批量补结算历史章节的叙事记忆（填数据空洞） | confirmed-write |\n| `chapter.discard_range` | 试写整段作废：从正史抹去章节结果与章域记忆 | destructive |\n| `outline.volume` | 维护卷纲（get/suggest/set）；当前卷目标进入 preflight | read/write |\n| `arc.character` | 查角色弧停滞或回退 | read |\n| `book.dissect` | 按规则拆已有旧书为续写知识包（产物为待确认档） | read/write |\n| `") },
        { title: t("`pipeline.write` 内部做什么？"), body: t("对外看是一次工具调用，内部会执行：\n\n1. 写前硬门：`write.preflight` 上下文门、相关 Writing Skills 加载提示、高风险 pending 事件策略、情节点预算复核（预算判 block 时直接返回 `beat-budget-invalid`，不浪费一次提交）。\n2. 组装 ContextCard：整合 sceneSpec、Lore、动态记忆、前文。Writing Skills 不走这条通道，由同一 Runtime 会话的 Skill 工具加载。\n3. 确定性章节审计（`chapter.audit` 规则）。\n4. 长度硬范围校验：超出本书硬区间返回 `length-out-of-range`，由当前 Agent 修订后重新提交。\n5. 保存前按启用技能做合规校验：硬性违规 `writing-skill-compliance-failed` 不保存，warning 级逐条进 `publishHint.warnings`。\n6. 投稿风险单章轻检：返回本地敏感词、AI 味、格式和连续性线索；只提示人工复核，不因平台口径阻断保存。\n7. 正文落盘为正式章节文件并更新索引，随后自动章后结算（确定性抽取叙事事件）。\n\n正文与蓝图必须由当前 Runtime Agent 显式提交；工具不在内部调用模型，也不另开 Writer/Auditor/Reviser Agent。写作技能的生效证据是同一会话的成功 Skill 调用记录，写后按技能规则硬校验。\n\n返回值里的可观测字段：\n\n- `publishHint.warnings`：逐条列出违反了哪个技能的哪条要求。\n- `settlementError`：正文已保存但章后结算失败，需对该章 `memory.settle_range` 补结算。正文不会因结算失败被丢弃。") },
        { title: t("正式章节结果机制"), body: t("```\npipeline.write → chapterId → 画布展示 → 正式章节继续编辑\n```\n\n- 正式章节结果附带 artifact，可在写作画布直接打开审阅。\n- 正式章节写入由用户裁决，不由 AI 自动覆盖。") },
        { title: t("上下文组装优先级"), body: t("1. Scene Spec 蓝图（本章目标与硬约束）\n2. Lore / 经纬静态设定（canon/rules/reference）\n3. Narrative Memory 动态 ContextCard（facts/timeline/hooks/state/style/semantic）\n4. 前文摘要与驾驶舱快照\n5. PGI 用户回答与作者指示\n6. 低优先级风格/预设/节拍提示") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [t("**跳过 `write.preflight` 直接写** → 错误。上下文没就绪时写出来的是编造的前情，返工成本比停一下高得多。"), t("**preflight 报 `empty-recent-progress` 却继续写** → 错误。先回填记忆，或确认那些章其实是废稿。"), t("**给废稿养正史** → 错误。整段作废用 `chapter.discard_range`，不要用 `memory.settle_range` 把废稿结算进正史。"), t("**跳过 `lore.read` / `memory.read`** → 容易丢静态设定或动态事实。"), t("**把写后事实写进 Lore** → 错误。章节摘要、关系变化、伏笔推进默认走 `memory.events`。"), t("**把机器抽取结果直接当 canon** → 错误。`book.dissect` 产物写 `needs-review`，作者确认后才升 canon。"), t("**PGI 无问题就停住** → 错误。应记录 `skippedReason=no-questions` 并继续 scene.spec。"), t("**按 code 自造拦截文案** → 错误。转述 `explanation` 三段式。")],
      agentHints: [t("写前入口：`write.preflight`（硬门，先于一切生成）。"), t("管线入口：`pipeline.write(sceneSpec)`。"), t("上下文入口：`lore.read + memory.read`。"), t("写后入口：`memory.events`；补历史用 `memory.settle_range`。"), t("发布入口：`publish.check`。"), t("安全原则：正式章节结果边界、用户确认、canon evidence 门禁。")],
      actions: [
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "agent-settings",
      category: "novelfork-settings",
      tags: ["Agent","设置","模型","推理","运行时","权限"],
      title: t("Agent 设置"),
      summary: t("会话模型、子代理模型池、推理强度、运行时控制、权限模式、超时配置"),
      sections: [
        { title: t("核心概念"), body: t("**默认模型**：所有叙述者会话使用的主模型。建议选能力最强的模型。\n\n**摘要模型**：对话压缩时使用的模型。可选较便宜的快速模型。\n\n**子代理模型池**：子代理（explore/plan/general/fork）可使用的模型列表。系统按任务类型自动选择。\n\n**推理强度**：控制 AI 思考深度。高推理强度适合复杂规划，低推理强度适合简单续写。\n\n**最大步数**：单次请求中 Agent 最多执行的工具调用步数。防止 Agent 无限循环。\n\n**首 token 超时**：API 请求超时后自动中断（0=禁用）。\n\n**权限模式（SessionPermissionMode）**：\n\n| 模式 | 说明 | 适用场景 |\n|------|------|---------|\n| `read` | 只读，禁止任何写入 | 探索、审计 |\n| `plan` | 可输出计划，不可执行 | 规划阶段 |\n| `ask` | 写入前弹窗确认 | 默认推荐 |\n| `edit` | 允许写作级写入 | 日常写作 |\n| `allow` | 全自动，无需确认 | 批量任务 |") },
        { title: t("超时配置"), body: t("| 参数 | 说明 | 建议值 |\n|------|------|--------|\n| 首 token 超时 | 等待 API 首个响应的最大时间 | 30-60 秒 |\n| 请求超时 | 单次 API 调用总超时 | 120-300 秒 |\n| 管线超时 | pipeline.write 整体超时 | 0（禁用） |") },
        { title: t("自定义重试规则"), body: t("支持按 HTTP 状态码或内容关键词匹配可重试错误：\n\n- 429（Rate Limit）：指数退避，最多 3 次\n- 502/503（网关错误）：立即重试 1 次后退避\n- 自定义关键词匹配：如 `overloaded`、`capacity`") },
      ],
      workflow: [],
      bestPractices: [t("写书 Agent 用最强模型，审校/伏笔 Agent 可用较快模型"), t("推理强度：规划大纲用高，日常续写用中，简单修改用低"), t("首 token 超时建议设 30-60 秒，避免 API 卡死时无限等待"), t("子代理模型池至少配 2 个模型，一个主力一个备用"), t("权限模式从 `ask` 开始，熟悉系统后再切换")],
      pitfalls: [t("**子代理无响应** → 子代理模型池为空或模型不可用"), t("**Agent 执行太慢** → 推理强度过高或模型响应慢，降低强度或换模型"), t("**Agent 无限循环** → 最大步数设太高，降低到 25-30"), t("**确认弹窗太频繁** → 权限模式从 `ask` 切到 `edit`")],
      agentHints: [t("运行时控制通过 `/api/settings/runtime` 读写"), t("推理强度映射到模型的 temperature / top_p 参数"), t("最大步数限制 Agent 单次请求的工具调用次数"), t("子代理继承父代理的供应商配置，但可独立选择模型"), t("权限模式决定工具的 `enabledForModes` 过滤——`read` 模式下 `draft-write` 和 `confirmed-write` 工具不可用"), t("自定义重试规则：按 HTTP 状态码或内容关键词匹配可重试错误")],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "proxy-settings",
      category: "novelfork-settings",
      tags: ["代理","网络","代理服务器","proxy"],
      title: t("代理设置"),
      summary: t("网络代理配置，解决 API 访问受限问题"),
      sections: [
        { title: t("核心概念"), body: t("**供应商代理**：为 AI API 请求配置 HTTP/SOCKS5 代理。当直连 API 端点受限时使用。\n\n**WebFetch 代理**：为网页抓取工具配置代理。当目标网站有地域限制时使用。\n\n**平台代理**：全局代理设置，影响所有出站请求。\n\n代理配置支持：\n- HTTP 代理：`http://host:port`\n- SOCKS5 代理：`socks5://host:port`\n- 认证代理：`http://user:pass@host:port`") },
      ],
      workflow: [],
      bestPractices: [t("只为需要代理的供应商配置，不必全局开启"), t("SOCKS5 代理性能优于 HTTP 代理"), t("代理不稳定时配置多个备用地址")],
      pitfalls: [t("**配置代理后仍然超时** → 代理服务器本身不可用，先用测试连接验证"), t("**部分供应商走代理部分不走** → 检查是否配置了供应商级别的代理覆盖"), t("**WebFetch 抓取失败** → 目标网站可能屏蔽了代理 IP")],
      agentHints: [t("代理配置存储在 settings store 的 proxy 字段"), t("供应商级代理优先于全局代理"), t("LLMClient 在发起请求时读取代理配置，通过 `https-proxy-agent` 实现"), t("WebFetch 工具独立读取 WebFetch 代理配置")],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "usage-history",
      category: "novelfork-settings",
      tags: ["使用量","Token","费用","统计","图表"],
      title: t("使用历史与 Token 账单"),
      summary: t("查看 AI 模型消耗量、请求明细、时间序列趋势与费用统计"),
      sections: [
        { title: t("功能概览"), body: t("使用历史面板（设置 → 使用历史）提供：\n\n| 功能 | 说明 |\n|------|------|\n| **筛选条件** | 按供应商、模型、请求类型、时间范围过滤 |\n| **统计卡片** | 请求数、Token 总数（输入/输出拆分）、缓存读/写、推理 Token、总费用、平均耗时、首 Token 时间 |\n| **时间序列图表** | Recharts 柱状图，按小时/天/月聚合，左轴 Token、右轴请求数/错误数 |\n| **请求明细表** | 分页列表，点击可查看单次请求的完整详情（模型、Token、耗时、状态码） |") },
        { title: t("数据来源"), body: t("- 后端从 SQLite `api_request` 表聚合，由 Runtime 在每次模型调用时自动记录。\n- 时间序列由 Runtime 服务端按 granularity（hour/day/month）桶化后返回。\n- NUG 反代的使用量通过 NUG 专属 API 独立查询（含通道级拆分）。") },
        { title: t("粒度切换"), body: t("| 粒度 | 适用 |\n|------|------|\n| 小时 | 近 24h 调用密度分析 |\n| 天 | 近 30 天日均消耗 |\n| 月 | 长期费用趋势 |") },
        { title: t("费用计算"), body: t("费用由各供应商 API 返回的 `usage.cost` 或按 Token 单价估算（部分供应商不返回精确费用）。\n费用列显示美元 (USD) 单位，精确到 4 位小数。") },
        { title: t("常见问题"), body: t("| 问题 | 原因与解决 |\n|------|-----------|\n| 费用显示 \"—\" | 该供应商未返回 cost 字段 |\n| 请求数量远大于章节数 | 包含工具调用、Context Compact、Sub-agent 等内部请求 |\n| 403 无权查看 | 需要 Runtime 管理员角色 |") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "appearance",
      category: "novelfork-settings",
      tags: ["外观","主题","侧栏","深色模式","配置"],
      title: t("外观与界面"),
      summary: t("主题切换、侧栏配置、字体与布局偏好"),
      sections: [
        { title: t("主题"), body: t("| 模式 | 说明 |\n|------|------|\n| 浅色 | 白底黑字 |\n| 深色 | 暗底亮字（默认推荐，长时间写作护眼） |\n| 跟随系统 | 自动随操作系统深色模式切换 |\n\n设置路径：设置 → 外观与界面 → 主题。") },
        { title: t("侧栏可配置显示/收纳"), body: t("侧栏左下角的全局导航入口支持自由配置：\n- **右键任意入口** → 切换为\"显示\"或\"收纳\"\n- 收纳的入口折叠在\"已收纳 (N)\"按钮下，点击展开\n- 配置持久化到本地 localStorage，跨会话保持\n\n默认显示：叙述者列表、套路、知识库、群聊  \n可收纳：定时任务、学习中心等低频入口") },
        { title: t("字体与间距"), body: t("在设置 → 外观中可调整：\n- 界面字体大小（默认 14px）\n- 代码字体（Geist Mono）\n- 编辑器行高") },
        { title: t("其他偏好"), body: t("| 偏好 | 说明 |\n|------|------|\n| 自动加载历史消息 | 打开叙述者会话时是否自动加载旧消息 |\n| 快速模式默认 | 新会话是否默认启用快速模式 |\n| Markdown 自动换行 | 消息中 Markdown 段落是否自动折行 |\n| 代码块自动换行 | 代码块是否自动折行（或水平滚动） |") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "runtime-capabilities",
      category: "novelfork-settings",
      tags: ["运行时","CLAUDE.md","压缩","安全","token","cache","容错"],
      title: t("运行时能力"),
      summary: t("CLAUDE.md 规则读取、LLM 压缩摘要、容错解析、上下文防御、Prompt Cache"),
      sections: [
        { title: t("CLAUDE.md 规则读取"), body: t("系统启动时自动加载三层规则文件，按优先级合并：\n\n1. **全局规则** `~/.novelfork/CLAUDE.md` — 适用于所有项目的通用偏好\n2. **项目规则** 项目根目录 `CLAUDE.md` — 当前书籍的专属设定\n3. **目录规则** `.claude/rules/*.md` — 细粒度规则，按目录生效\n\n规则注入到 Agent 上下文中，编辑对应文件后下次对话自动生效。") },
        { title: t("XML tool_use 容错解析"), body: t("部分模型在版本回退时可能输出非标准的 XML 格式工具调用（而非 JSON）。系统自动检测并解析 XML 格式的 tool_use 块，无需用户干预即可正常执行工具调用。这是对模型 regression 的自动防御。") },
        { title: t("上下文中毒防御"), body: t("当对话上下文中混入恶意指令（如通过工具输出注入的 prompt injection），系统会自动检测异常模式并过滤。确保 Agent 行为始终受系统提示约束，不被外部内容劫持。") },
        { title: t("Token 与超时配置"), body: t("| 参数 | 值 | 说明 |\n|------|----|------|\n| max_tokens | 32768 | 单次回复的默认最大 token 数 |\n| max_tokens (escalation) | 65536 | 截断时自动升级到 64K |\n| 工具执行超时 | 120 秒 | 所有工具调用的统一超时 |\n| agent-turn-runtime | 120 秒 | 单轮 Agent 执行的总超时 |") },
        { title: t("max_output_tokens 恢复机制"), body: t("当模型回复因 token 不足被截断时，系统自动执行恢复：\n\n1. **检测截断** — `stop_reason === \"max_tokens\"` 时触发\n2. **重试 3 次** — 使用相同上下文重新请求，每次检查是否完整\n3. **Escalation** — 3 次仍截断，自动将 max_tokens 从 32768 提升到 65536 再试\n4. **最终失败** — 提升后仍截断则标记为部分结果，通知用户\n\n用户无需干预，日志中可见 `[max-tokens-recovery]` 条目。") },
        { title: t("Model Fallback（自动切备用模型）"), body: t("当主模型不可用时，系统自动尝试备用供应商：\n\n| 触发条件 | 行为 |\n|----------|------|\n| HTTP 503 / 529 (过载) | 等待 5s → 重试 → 失败则切备用 |\n| HTTP 429 (限流) | 读取 retry-after → 重试 → 超时切备用 |\n| 连接超时 (30s) | 直接切备用 |\n| 模型不存在 (404) | 报错，不切备用 |\n\n切换逻辑：按用户在设置中配置的供应商优先级顺序尝试，第一个可用的即采用。切换时 UI 状态栏短暂显示\"已切换到备用模型\"。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [t("CLAUDE.md 加载顺序：全局 → 项目 → 目录规则，后者覆盖前者"), t("压缩摘要使用独立的摘要模型（在 Agent 设置中配置）"), t("Staleness check 基于文件 mtime 比较"), t("Dedup 基于文件路径 + 内容 hash"), t("Prompt Cache 对 Anthropic 模型自动启用，其他供应商不支持"), t("二进制检测基于文件头 magic bytes"), t("XML tool_use 容错：自动检测 `<tool_use>` XML 块并解析为标准工具调用"), t("上下文中毒防御：过滤工具输出中的 prompt injection 模式"), t("max_tokens 默认 32768，截断时 escalation 到 65536（3 次重试 + 升级）"), t("Model Fallback：503/429/超时自动切备用供应商"), t("Budget Pressure：70%/80%/92%/97% 四级，92% 以上注入精简指令"), t("In-flight Microcompact：60% 时折叠本轮早期工具结果"), t("工具超时与 agent-turn-runtime 均为 120 秒")],
      actions: [
      ],
    },
    {
      id: "subagent-system",
      category: "novelfork-settings",
      tags: ["子代理","subagent","ForkNarrator","Send","Await","Recall","TaskCreate","Pipeline"],
      title: t("子代理系统"),
      summary: t("ForkNarrator 分叉、Send 通信、Await 等待、Recall 记忆、TaskCreate 任务管理、Pipeline 工具"),
      sections: [
        { title: t("核心概念"), body: t("### 四种内置类型\n\n| 类型 | 用途 | 特点 |\n|------|------|------|\n| explore | 搜索和阅读代码/文档 | 只读，不修改文件 |\n| plan | 规划方案和设计架构 | 输出计划，不执行实现 |\n| general | 通用任务执行 | 可读写文件、运行命令 |\n| fork | 继承当前上下文的分支 | 携带父对话的完整记忆 |\n\n### 高级工具\n\n| 工具 | 功能 | 说明 |\n|------|------|------|\n| **ForkNarrator** | 分叉独立叙述者 | 创建独立的叙述者会话，有自己的上下文和工具权限 |\n| **Send** | 跨代理消息 | 向后台运行的子代理或兄弟代理发送消息 |\n| **Await** | 等待结果 | 等待后台任务完成并获取结果，支持超时 |\n| **Recall** | 记忆检索 | 搜索历史对话和上下文，找到之前讨论过的内容 |\n| **TaskCreate** | 任务管理 | 创建和管理待办任务列表 |\n| **Pipeline** | 写作管线 | 调用小说写作工具链（pipeline.write 等） |") },
        { title: t("ForkNarrator 详解"), body: t("ForkNarrator 创建一个独立的叙述者分支，适合需要完全隔离的场景：\n\n```\n主叙述者 → ForkNarrator(\"尝试修仙风格写第三章\")\n         → 新叙述者独立运行\n         → 结果满意 → 采纳\n         → 不满意 → 丢弃，主叙述者不受影响\n```\n\n与 fork 子代理的区别：\n- **fork 子代理**：临时任务，完成后回收，结果汇报给父代理\n- **ForkNarrator**：创建持久的独立叙述者，有独立的对话历史和生命周期") },
        { title: t("Send 消息通信"), body: t("Send 工具实现子代理间的异步通信：\n\n```\n主代理 → Send(targetId, \"已完成大纲，请开始写第一章\")\n子代理 ← 收到消息，开始执行\n```\n\n使用场景：\n- 协调多个后台子代理的工作顺序\n- 向正在运行的子代理追加指令\n- 兄弟代理间的信息传递") },
        { title: t("Await 等待机制"), body: t("等待后台任务完成并获取结果：\n\n```\n// 派发后台任务\nAgent(type=\"general\", background=true, id=\"scan-task\")\n\n// 稍后获取结果\nAwait(id=\"scan-task\", timeout=60000)\n```\n\n- 支持超时设置（毫秒）\n- 超时后返回当前已有的部分结果\n- 未超时时阻塞直到任务完成") },
        { title: t("Recall 记忆检索"), body: t("搜索历史对话，找到之前讨论过的内容：\n\n```\nRecall(\"上次讨论的修仙体系\")\n→ 返回匹配的历史对话片段\n```\n\n适用于：\n- 找回之前讨论过但没有写入经纬的设定想法\n- 回顾之前的写作决策和理由\n- 跨会话的信息检索") },
        { title: t("TaskCreate 任务管理"), body: t("创建结构化任务列表，跟踪写作进度：\n\n```\nTaskCreate([\n  { id: \"ch5\", content: \"写第五章\", status: \"pending\" },\n  { id: \"audit\", content: \"审计第四章\", status: \"in_progress\" },\n])\n```\n\n任务状态：`pending` → `in_progress` → `completed`") },
      ],
      workflow: [],
      bestPractices: [t("explore 代理适合\"帮我查一下前面哪章提到过这个角色\""), t("后台任务适合批量检查，完成后用 Await 获取结果"), t("ForkNarrator 适合\"试试另一种写法\"——完全隔离，不满意直接丢弃"), t("Recall 用于找回之前讨论过的想法，避免重复决策"), t("TaskCreate 用于规划多步骤写作计划")],
      pitfalls: [t("**子代理无响应** → 检查子代理模型池配置是否有可用模型"), t("**后台任务结果丢失** → 未使用 Await 获取结果。任务完成后结果仍可查询"), t("**ForkNarrator 上下文过大** → 继承了父对话全部历史，考虑先 `/compact` 再分叉"), t("**Send 消息未送达** → 目标代理已完成或被回收")],
      agentHints: [t("子代理通过 `Agent` 工具派发，`Await` 工具等待结果"), t("`ForkNarrator` 创建独立叙述者，有持久生命周期"), t("`Send` 工具可向后台运行的子代理或兄弟代理发送消息"), t("`Recall` 工具搜索历史对话上下文"), t("`TaskCreate` 工具管理结构化待办列表"), t("`Pipeline` 工具调用小说写作管线（pipeline.write 等）"), t("子代理继承父代理的供应商配置和套路设置"), t("后台任务生命周期：派发（background=true） → 运行 → Await 获取结果"), t("MCP 工具自动继承父代理配置"), t("自定义子代理在套路的 SubAgents tab 中定义")],
      actions: [
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "tool-search-and-skills",
      category: "novelfork-settings",
      tags: ["工具","搜索","技能","Skills","MCP","权限"],
      title: t("工具、搜索与技能"),
      summary: t("Agent 工具执行机制、搜索能力与技能系统全景"),
      sections: [
        { title: t("工具系统"), body: t("Agent 可调用的工具分三类：\n\n| 类型 | 说明 | 示例 |\n|------|------|------|\n| **内置工具** | Runtime 核心能力 | Read、Write、Bash、Browser、Terminal |\n| **领域工具** | novel-plugin 注册的写作工具 | write.preflight、scene.spec、pipeline.write、lore.read、memory.read |\n| **MCP 工具** | 外部 MCP Server 暴露的能力 | 数据库查询、API 调用、自定义脚本 |") },
        { title: t("搜索能力"), body: t("| 搜索类型 | 后端 | 用途 |\n|----------|------|------|\n| 文件搜索 | ripgrep (rg) | 代码与文本文件内容搜索 |\n| Web 搜索 | Tavily / Bocha / 智谱 / 自定义 HTTP | 联网获取最新信息 |\n| 叙事记忆搜索 | SQLite LIKE 匹配 | 搜索动态事实与事件 |\n| 经纬搜索 | 全文 + 分类过滤 | 搜索静态设定条目 |") },
        { title: t("技能系统 (Skills)"), body: t("### 全局技能 vs 作品技能\n- **全局技能**：扫描 `~/.novelfork/skills/` 以及 Runtime 兼容的 `~/.narrafork/skills/`、`~/.claude/skills/`、`~/.agents/skills/`。对所有叙述者生效。\n- **作品技能**：自动扫描作品目录 `.novelfork/skills/`。通过书籍可信绑定访问，仅对该作品生效；文件存在即参与解析。\n\n### 技能文件结构\n\n每个技能是一个目录，包含 `SKILL.md`：\n\n```\n~/.novelfork/skills/my-skill/\n├── SKILL.md          ← 主文件（Frontmatter + Prompt）\n└── templates/        ← 可选辅助模板\n    └── example.md\n```\n\n### 在线浏览与预览\n\n在\"套路 → 技能\"页面：\n- 每个 Skill 卡片可展开文件树，列出包含的所有文件。\n- 点击文件名弹窗在线查看源码与 Markdown 格式化内容。\n- 支持创建、编辑、删除全局或作品级技能。\n\n### 写作技能 (Writing Skills)\n\n属于独立子系统（见 `19-presets-and-beats.md`），专注于写作规则与合规检查。\n作品目录中的 `.novelfork/skills/` 文件会被自动发现并解释；面板的添加/删除操作只是对这些文件执行增量同步。") },
        { title: t("工具权限"), body: t("每个工具的执行受权限模式控制：\n\n| 模式 | 行为 |\n|------|------|\n| `allow` | 自动执行，不询问 |\n| `ask` | 每次执行前弹出确认 |\n| `deny` | 禁止执行 |\n\n可在\"套路 → 工具权限\"中按 pattern 配置规则。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/routines"), href: "/next/routines" },
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "security-and-sandbox",
      category: "novelfork-settings",
      tags: ["安全","沙箱","白名单","权限","隔离"],
      title: t("安全与沙箱"),
      summary: t("三级沙箱隔离、目录白名单、命令白名单、权限模式"),
      sections: [
        { title: t("核心概念"), body: t("**沙箱模式**（三级隔离）：\n\n| 级别 | 说明 |\n|------|------|\n| none | 无隔离，Agent 可访问系统任意资源 |\n| basic | 基础隔离，限制文件访问范围和命令执行 |\n| strict | 严格隔离，仅允许白名单内的目录和命令 |\n\n**目录白名单**：Agent 可读写的目录列表。strict 模式下只有白名单内的路径可访问。\n\n**命令白名单**：Agent 可执行的 shell 命令列表。strict 模式下只有白名单内的命令可运行。\n\n**权限模式**：\n- `ask-always`：每次写入操作都需要用户确认\n- `auto-approve`：低风险操作自动批准，高风险仍需确认") },
        { title: t("Secret Detector（密钥自动脱敏）"), body: t("系统内置 20+ 模式匹配规则，自动检测并脱敏敏感信息：\n\n| 检测类型 | 示例模式 |\n|----------|----------|\n| API Key | `sk-...`, `key-...`, `AKIA...` |\n| Token | `ghp_...`, `gho_...`, `Bearer ...` |\n| 私钥 | `-----BEGIN RSA PRIVATE KEY-----` |\n| 连接字符串 | `postgresql://user:pass@...` |\n| 密码字段 | `password=...`, `secret=...` |\n| AWS 凭证 | `AKIAIOSFODNN7EXAMPLE` |\n| JWT | `eyJ...` (base64 header.payload.signature) |\n\n**脱敏行为**：\n- 工具输出中检测到的密钥替换为 `[REDACTED:key_type]`\n- Agent 上下文中永远看不到原始密钥值\n- 日志中同样脱敏，防止持久化泄露\n- 用户可在设置中查看被脱敏的条目计数") },
        { title: t("Path Sandbox（路径沙箱）"), body: t("文件操作（read/write/edit/glob/grep）在执行前校验路径：\n\n- **工作目录约束**：所有相对路径解析后必须在项目工作目录内\n- **符号链接追踪**：resolve 后检查真实路径是否越界\n- **路径穿越防御**：拦截 `../../etc/passwd` 等穿越尝试\n- **绝对路径检查**：绝对路径必须在白名单目录内（basic/strict 模式）\n\n违规时返回 `PATH_OUTSIDE_SANDBOX` 错误，不执行操作。") },
        { title: t("DANGEROUS_PATTERNS（危险命令拦截）"), body: t("24 条正则规则，在命令执行前拦截已知危险模式：\n\n| 类别 | 示例规则 |\n|------|----------|\n| 系统破坏 | `rm -rf /`, `mkfs`, `dd if=` |\n| Fork bomb | `:(){ :\\|:& };:`, `./$0\\|./$0&` |\n| 关机/重启 | `shutdown`, `reboot`, `init 0` |\n| 网络外传 | `curl.*\\|sh`, `wget.*\\|bash`（pipe-to-shell） |\n| 权限提升 | `chmod 777`, `sudo su` |\n| 凭证访问 | `cat ~/.ssh/id_rsa`, `cat /etc/shadow` |\n| 环境篡改 | `export PATH=`, `unset PATH` |\n| 批量删除 | `find . -delete`, `git clean -fdx` |\n\n**拦截行为**：\n- 匹配到危险模式时阻断执行，返回警告\n- 用户可手动确认放行（ask-always 模式下）\n- auto-approve 模式下危险命令仍需确认，不自动放行") },
      ],
      workflow: [],
      bestPractices: [t("日常写作用 basic 模式即可，限制在作品目录内"), t("不信任的 MCP 工具用 strict 模式隔离"), t("auto-approve 只在完全信任当前流程时使用")],
      pitfalls: [t("**Agent 报权限不足** → 沙箱模式过严，检查白名单是否包含需要的路径"), t("**命令执行被拒绝** → strict 模式下命令不在白名单中，添加到允许列表"), t("**切换模式后不生效** → 需要重新创建会话或重启服务")],
      agentHints: [t("沙箱配置在 settings store 的 sandbox 字段"), t("目录白名单通过 `directoryAllowlist` 配置"), t("命令白名单通过 `commandAllowlist` 配置"), t("权限检查在工具执行前由 PermissionGate 拦截"), t("strict 模式下未列入白名单的操作直接拒绝，不弹确认门"), t("Secret Detector：20+ 模式自动脱敏，Agent 永远看不到原始密钥"), t("Path Sandbox：所有文件操作路径必须在工作目录/白名单内"), t("DANGEROUS_PATTERNS：24 条规则拦截危险命令，auto-approve 下仍需确认")],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "browser-and-terminal",
      category: "novelfork-settings",
      tags: ["浏览器","终端","截图","headless","进程"],
      title: t("浏览器与终端"),
      summary: t("Browser 截图交互、Terminal 持久化进程管理"),
      sections: [
        { title: t("Browser 工具"), body: t("Agent 可通过 Browser 工具操作 headless 浏览器：\n\n- **截图**：捕获网页当前状态的截图\n- **导航**：打开指定 URL\n- **交互**：点击、输入、滚动等基本操作\n\n使用系统已安装的 Chrome 或 Edge（headless 模式），无需额外安装浏览器。") },
        { title: t("Terminal 工具与 Web 交互终端"), body: t("Agent 可创建和管理持久化终端进程：\n\n- **创建进程**：启动长时间运行的命令（如 dev server）\n- **读取输出**：获取进程的 stdout/stderr\n- **发送输入**：向进程 stdin 写入\n- **网页内嵌终端 (xterm.js)**：在“设置 → 终端”页面中，支持直接在网页端附加并交互操作运行中的 dtach / PTY 终端会话，支持实时 ANSI 色彩、大小自适应与 WebSocket 输出回放。\n\n与 Bash 工具的区别：Bash 是一次性执行命令并返回结果；Terminal 是持久化进程，可持续交互。") },
        { title: t("消息网关 (Gateway)"), body: t("在“设置 → 消息网关”中，可配置多平台机器人与 Webhook 连接：\n- 支持 Telegram、Discord、Slack、飞书、Webhook、微信与 QQ Bot；\n- 微信通道支持**网页二维码扫码登录与自动授权**；\n- 支持全局网关启停、默认权限模式与会话超时设定。") },
      ],
      workflow: [],
      bestPractices: [t("Browser 截图用于前端 QA 验证"), t("Terminal 适合需要持续运行的后台服务"), t("不要同时开太多 Terminal 进程，注意资源占用")],
      pitfalls: [t("**Browser 截图失败** → 系统未安装 Chrome/Edge，或路径未正确配置"), t("**Terminal 进程意外退出** → 检查命令是否正确，查看 stderr 输出"), t("**Browser 页面空白** → 目标页面需要 JavaScript 渲染，等待加载完成后再截图")],
      agentHints: [t("Browser 工具使用 Puppeteer 协议连接系统 Chrome/Edge"), t("Terminal 进程通过 PTY 管理，支持 ANSI 转义序列"), t("Browser 截图返回 base64 图片，可直接在对话中展示"), t("Terminal 输出有缓冲区大小限制，超出后自动截断旧内容"), t("两个工具都受沙箱模式约束")],
      actions: [
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "web-tools",
      category: "novelfork-settings",
      tags: ["网络","搜索","抓取","WebSearch","WebFetch"],
      title: t("网络工具"),
      summary: t("WebSearch 搜索引擎、WebFetch 四种模式网页抓取"),
      sections: [
        { title: t("核心概念"), body: t("**WebSearch**：Agent 可搜索互联网获取最新信息。用于查找写作参考资料、验证事实、获取灵感。\n\n**WebFetch**：从指定 URL 获取网页内容。四种模式：\n\n| 模式 | 说明 | 适用场景 |\n|------|------|---------|\n| readability | 提取文章正文 | 博客、新闻、文档 |\n| screenshot | 截图 | 需要看页面布局 |\n| dom | 提取 HTML 结构 | 表格、列表等结构化数据 |\n| smart | AI 摘要 | 长页面只需关键信息 |") },
      ],
      workflow: [],
      bestPractices: [t("搜索写作参考时明确关键词，如\"修仙小说 金丹期 突破描写\""), t("WebFetch 优先用 readability 模式，最干净"), t("长页面用 smart 模式让 AI 提取关键信息，省 token")],
      pitfalls: [t("**搜索无结果** → 关键词太宽泛或网络不通，缩小搜索范围"), t("**WebFetch 返回空** → 目标网站需要 JavaScript 渲染，尝试 screenshot 模式"), t("**抓取被拒绝** → 目标网站有反爬机制，配置代理或换源")],
      agentHints: [t("WebSearch 返回搜索结果列表（标题 + URL + 摘要）"), t("WebFetch 的 readability/dom/smart 模式不需要浏览器，直接 HTTP 请求"), t("WebFetch 的 screenshot 模式需要 Chrome/Edge（同 Browser 工具）"), t("两个工具都受代理设置影响（WebFetch 代理配置）"), t("smart 模式可传 `purpose` 参数指导 AI 提取方向"), t("输出有长度限制（默认 20000 字符），可通过 `max_length` 调整")],
      actions: [
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "presets-and-beats",
      category: "novelfork-advanced",
      tags: ["写作技能","Skills","合规","文风","规则","SKILL.md"],
      title: t("写作技能 (Writing Skills)"),
      summary: t("取代旧 Preset/Beat 的写作规则系统，支持合规检查、文件树浏览与作品级物化"),
      sections: [
        { title: t("核心概念"), body: t("**Writing Skill** 是一个包含 `SKILL.md`（Frontmatter + Prompt）的独立文件夹。每个 Skill 定义了一组写作规则、合规检查或结构模板，Agent 在写作时会遵守已启用的 Skills。\n\n| 字段 | 说明 |\n|------|------|\n| `id` | 全局唯一标识 |\n| `name` | 显示名称 |\n| `kind` | 类型：`style` / `workflow` / `character` / `plot` / `structure` |\n| `mode` | `always`（始终生效）/ `manual`（项目级启用） |\n| `checks` | 声明式合规检查规则（required-terms / forbidden-terms / pattern） |") },
        { title: t("三级来源"), body: t("| 来源 | 路径 | 优先级 |\n|------|------|--------|\n| 内置 | 产品 `skills/` 目录（编译时内联） | 最低 |\n| 作者级 | `~/.novelfork/skills/<slug>/` | 中（同 slug 覆盖内置） |\n| 作品级 | 作品根目录 `.novelfork/skills/<slug>/` | 最高；文件自动发现 |") },
        { title: t("作品级自动发现与文件操作"), body: t("1. `.novelfork/skills/<slug>/SKILL.md` 是作品级 Writing Skill 的唯一规范路径；Runtime、preflight、工具解析和 UI 都直接扫描该目录。\n2. 目录中的每个技能文件都会自动解释并参与当前作品写作，文件是否存在就是生效状态，不需要 `book.json` 字段绑定。\n3. 写作配置面板的开关只负责对 catalog Skill 执行文件增删；刷新操作才会用 catalog 原文覆盖已有项目文件。\n4. 作品内直接编辑 `SKILL.md` 或附件即可形成该作品的独立规则，作者级覆盖和内置版本不会被反向修改。") },
        { title: t("文件树浏览与预览"), body: t("在\"套路 → 全局技能 / 作品技能\"页面：\n- 每个 Skill 卡片可点击展开文件树，列出内部所有文件。\n- 点击文件名可在弹窗中在线预览 Markdown/代码源码。") },
        { title: t("合规检查 (Compliance Checks)"), body: t("在 `SKILL.md` 的 `checks` 字段声明式定义规则：\n\n```yaml\nchecks:\n  - type: required-terms\n    terms: [\"伏笔\", \"节奏\"]\n    message: 本章缺少关键叙事要素\n  - type: forbidden-terms\n    terms: [\"不禁\", \"莫名\"]\n    severity: error\n  - type: pattern\n    pattern: \"(.)\\1{4,}\"\n    message: 连续重复超过 4 次\n```\n\n写作结束后系统自动执行合规检查，违规项会在写作视图中提示修正。") },
        { title: t("与旧 Preset/Beat 的关系"), body: t("| 旧概念 | 新对应 |\n|--------|--------|\n| Preset | `kind: style` 的 Writing Skill |\n| Beat Template | `kind: structure` + `kind: plot` 的 Writing Skill |\n| 自定义 Preset | 编辑 Skill → fork 到作者目录 |\n| 全局启用 | `mode: always` |\n| 作品级生效 | `mode: manual` + `.novelfork/skills/` 中存在对应文件 |\n\n`book.json` 不保存 Writing Skill 的启用列表；旧 `enabledWritingSkillIds`、`enabledPresetIds`、`beatTemplateId` 等字段不参与运行时判定。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      { label: t("前往"), description: t("/next/routines"), href: "/next/routines" },
      ],
    },
    {
      id: "book-narrators",
      category: "novelfork-advanced",
      tags: ["叙述者","会话","书籍","绑定","多会话"],
      title: t("书籍叙述者"),
      summary: t("每本书自带不可删除的叙述者会话，支持多会话切换与书籍绑定工具"),
      sections: [
        { title: t("核心机制"), body: t("- **自动创建**：创建新书时自动绑定一个叙述者会话（不可删除）。\n- **可信书籍绑定**：叙述者通过服务端绑定解析作品路径，前端或 AI 模型无法直接构造路径。\n- **书籍级工具**：绑定后的叙述者自动拥有写作领域工具（chapter.read、lore.read、memory.read、cockpit.snapshot、pipeline.write 等）。\n- **多会话**：同一本书可以有多个叙述者会话（如主线写作会话 + 实验性改动会话），在工作台顶部切换。") },
        { title: t("叙述者能力"), body: t("| 能力 | 说明 |\n|------|------|\n| 读取经纬 | 访问书籍全部静态设定 |\n| 读取叙事记忆 | 检索动态事实与事件 |\n| 读写章节 | 写入新章 / 修改已有章节 |\n| 写前预检 | write.preflight 检测是否满足写章条件 |\n| 合规检查 | 调用 Writing Skills 声明的合规规则 |\n| 工具执行 | 经纬条目创建/更新、伏笔管理、导入拆书等 |\n| 权限确认 | 破坏性操作（删除、覆盖）需用户手动确认 |") },
        { title: t("会话状态"), body: t("| 状态 | 含义 |\n|------|------|\n| `running` | 正在执行（Agent 工作中） |\n| `idle` | 等待用户输入 |\n| `archived` | 已归档（可在设置 → 存储中清理） |") },
        { title: t("与写作视图的关系"), body: t("写作视图（WriteViewPanel）的\"写蓝图\"/\"直接写章\"按钮通过 `onSendToNarrator` 向当前活跃叙述者发送消息，叙述者负责执行完整写作管线并在权限框架内操作。") },
        { title: t("常见问题"), body: t("| 问题 | 说明 |\n|------|------|\n| 叙述者无响应 | 检查 AI 供应商是否配置且可用 |\n| 写章按钮不可用 | write.preflight 未通过（缺少设定/经纬/指示） |\n| 想删除叙述者 | 书籍叙述者不可删除，但可新建替代会话 |") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      { label: t("前往"), description: t("/next/narrators/:id"), href: "/next/narrators/:id" },
      ],
    },
    {
      id: "agent-behavior-rules",
      category: "novelfork-advanced",
      tags: ["Agent","行为","规范","验证","Bash"],
      title: t("Agent 行为规范"),
      summary: t("失败循环检测、默认行动决策、验证流程、Bash 规则、上下文压缩感知"),
      sections: [
        { title: t("失败循环检测"), body: t("同一种方法连续失败 2 次后，Agent 必须停下来：\n\n1. 诊断根因（不再做增量修补）\n2. 解释失败原因\n3. 提出完全不同的方案\n4. 征求用户确认后再继续\n\n不允许同一条路反复试错超过 2 次。") },
        { title: t("默认行动决策"), body: t("Agent 优先行动，不只是建议：\n\n| 场景 | 行为 |\n|------|------|\n| 小改动（改名、修 typo、单文件调整） | 直接做，不问 |\n| 中等改动（多文件、陌生代码） | 先读相关代码，再实施 |\n| 大改动（架构调整、新模块） | 先说方案，等确认再动手 |\n| 分析/比较类请求 | 只输出分析，不动代码 |\n\n不确定时，推断最可能的有用行动并执行，通过读代码补充缺失信息，而非猜测。") },
        { title: t("验证流程"), body: t("每次代码改动后必须验证：\n\n1. **编译检查** — 运行项目构建，确保无报错\n2. **功能验证** — 运行相关测试或实际操作确认行为正确\n3. **前端改动** — 必须截图确认 UI 正确\n4. **后端改动** — 必须 curl 实测确认 API 正确\n\n验证发现问题时当场修复，不交给用户。") },
        { title: t("Bash 使用规则"), body: t("| 规则 | 说明 |\n|------|------|\n| 超时处理 | 预计超过 30 秒的命令必须 `run_in_background` |\n| 禁止甩锅 | 不要让用户手动执行命令，Agent 自己执行 |\n| 实时输出 | 长命令使用后台模式 + 轮询结果 |\n| 路径安全 | Windows 下用 Git Bash 语法，注意路径转义 |") },
        { title: t("上下文压缩感知"), body: t("当上下文窗口被压缩（compaction）后：\n\n- Agent 不依赖记忆中\"之前做了什么\"\n- 主动检查文件状态和命令输出确认当前进度\n- 如果在多步任务中间被压缩，从检查点重新确认后继续\n\n这确保压缩不会导致错误操作或重复工作。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [t("失败循环：2 次同类失败 → 停下诊断 → 换方法 → 征求确认"), t("默认行动：小改动直接做，大改动先确认，分析类不动代码"), t("验证是交付条件：未验证 = 未完成"), t("Bash 30 秒规则：dev server、编译等长命令必须后台运行"), t("压缩后：读文件/跑命令确认状态，不靠记忆")],
      actions: [
      ],
    },
    {
      id: "new-book-guide",
      category: "novelfork-advanced",
      tags: ["新书","引导","十一问","经纬","Writing Skills","创作"],
      title: t("新书引导（建书十一问）"),
      summary: t("创建新书后通过十一问收集创作意图，自动推荐写作技能与生成经纬骨架"),
      sections: [
        { title: t("工作原理"), body: t("1. **创建书籍**：在首页点击\"新建作品\"，填写书名和简介。\n2. **十一问引导**：系统自动展示 11 个结构化问题（题材、受众、主角、核心冲突、世界设定、篇幅目标等）。\n3. **AI 推荐写作技能**：根据答案匹配适合的 Writing Skills（如\"冲突与悬念分工\"、\"人物一致性守则\"等），作者确认后启用。\n4. **生成经纬骨架**：AI 根据答案自动创建经纬条目（角色、世界规则、卷纲草案），标注为 `layer=dynamic, status=needs-review`。\n5. **进入写作工作台**：引导完成后刷新资源树，作者可直接开始写第一章。") },
        { title: t("十一问内容"), body: t("| 序号 | 问题 | 用途 |\n|------|------|------|\n| 1 | 什么题材/类型？ | 匹配 Writing Skills |\n| 2 | 目标平台？ | 合规基线选择 |\n| 3 | 预计总字数？ | 卷纲规划 |\n| 4 | 主角是谁？ | 角色经纬生成 |\n| 5 | 核心冲突？ | 伏笔与弧线种子 |\n| 6 | 世界设定关键点？ | 世界规则经纬 |\n| 7 | 写作风格偏好？ | Style Skills 筛选 |\n| 8 | 更新频率？ | 日更目标配置 |\n| 9 | 是否有大纲？ | 卷纲导入 vs 生成 |\n| 10 | 已有多少存稿？ | 导入流程触发 |\n| 11 | 特殊要求？ | 自定义 Rules 注入 |") },
        { title: t("与写作技能的联动"), body: t("引导结束后：\n- 推荐的 Skills 只是建议，作者确认后由 `handleWritingSkillsWrite` 直接同步到当前项目磁盘。\n- Skill 及其关联附件同步到作品的 `.novelfork/skills/<slug>/`；Runtime 会自动发现文件，`book.json` 不保存启用态。\n- 作者可在\"写作配置 → 技能\"中随时调整，面板只对指定项目文件执行添加、删除或刷新。") },
        { title: t("与旧版建书的区别"), body: t("| 旧版 (v2.x) | 新版 (v3.3+) |\n|---|---|\n| 10 个自由文本问题 | 11 个结构化问题 + 类型化选项 |\n| 直接生成经纬 Markdown 文件 | 生成经纬条目（数据库存储） + Writing Skills 推荐 |\n| 无质量验证 | 生成后标注 `needs-review`，作者确认后升 canon |\n| 无 Skill 联动 | 自动推荐并启用匹配的写作技能 |") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/books"), href: "/next/books" },
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "context-management",
      category: "novelfork-advanced",
      tags: ["上下文","压缩","记忆","token","compact"],
      title: t("上下文管理"),
      summary: t("理解 AI 的记忆机制：压缩、清空、budget pressure、microcompact"),
      sections: [
        { title: t("什么是上下文？"), body: t("上下文是 AI 每次回复时能看到的全部信息，包括：\n\n- **系统提示**：Agent 的角色定义、工具说明、经纬数据\n- **历史消息**：你和 AI 之间的对话记录\n- **工具结果**：AI 调用工具后返回的内容（文件内容、搜索结果等）\n\n所有这些拼在一起，就是 AI 的\"工作记忆\"。它没有对话之外的记忆——看不到的就不存在。") },
        { title: t("上下文百分比是什么？"), body: t("状态栏的圆环显示当前上下文占模型窗口的比例：\n\n- **30%**：空间充裕，正常对话\n- **60%**：已经积累了不少内容，仍可正常使用\n- **80%**：较满，建议关注\n- **95%+**：接近极限，需要处理\n\n不同模型的窗口大小不同（如 Claude 200K、DeepSeek 128K），同样的对话在小窗口模型上会更快填满。") },
        { title: t("为什么 AI 会\"忘记\"？"), body: t("AI 不会真的忘记——它只是看不到了。当上下文超过窗口时：\n\n- 早期消息被**压缩**为摘要（保留核心信息，丢失细节）\n- 或者被**截断**（直接不发送给模型）\n\n所以 AI 可能忘记你 20 条消息前提到的细节，这不是 bug，是物理限制。") },
        { title: t("四级 Budget Pressure"), body: t("系统根据上下文占比自动分级响应：\n\n| 阈值 | 级别 | 表现 |\n|------|------|------|\n| 70% | info | 圆环变黄，提示\"上下文较满\" |\n| 80% | warning | 建议你压缩或开新 session |\n| 92% | urgent | AI 自动精简回复、减少工具调用 |\n| 97% | blocked | 阻断发送，强制你处理上下文 |\n\n92% 以上时 AI 会收到系统指令要求\"节约 token\"，回复可能变短、不再主动展开。这是正常的自我保护行为。") },
        { title: t("\"清空上下文\"做了什么？"), body: t("点击\"清空上下文\"后：\n\n- 设置一个 cutoff 标记，cutoff 之前的消息**不再发送给模型**\n- UI 中旧消息仍然可见（可以回看）\n- 等同于开始一段\"新对话\"，但保留在同一个 session 内\n- AI 从此刻起看不到之前的任何对话内容\n\n适用场景：话题已切换，旧内容不再相关。") },
        { title: t("\"立即压缩\"做了什么？"), body: t("点击\"立即压缩\"后：\n\n1. 系统调用摘要模型读取当前全部对话\n2. 生成一份精炼摘要（通常 500-2000 token）\n3. 摘要替换原始对话历史，注入到下一次请求\n4. UI 中显示\"已压缩\"标记\n\n**保留的内容**：关键决策、人物名字、剧情要点、用户偏好\n**丢失的内容**：具体措辞、中间讨论过程、工具调用细节") },
      ],
      workflow: [],
      bestPractices: [t("**新话题开新 session**：而非在旧 session 中继续无关话题，避免无用上下文占空间"), t("**经常观察上下文圆环**：80% 以上主动压缩，不要等到 97% 被阻断"), t("**经纬数据不占对话上下文**：设定存在数据库里，按需注入当前场景相关的部分"), t("**长篇写作选大窗口模型**：200K 窗口比 128K 多 50% 的工作空间"), t("**定期开新 session**：每 3-5 章或每次大方向调整时，开新会话从头开始")],
      pitfalls: [t("**\"AI 突然忘了设定\"** → 上下文被压缩，设定细节在摘要中丢失。解决：把核心设定写入经纬"), t("**\"上下文 100% 了\"** → 只能清空或压缩，无法继续发送消息"), t("**\"压缩后 AI 行为变了\"** → 摘要可能遗漏了某些偏好，在新消息中重申即可")],
      agentHints: [t("上下文百分比计算：当前 token 数 / 模型 context_window"), t("压缩摘要使用 settings 中配置的摘要模型"), t("Microcompact 阈值 60%，保留最近 3 个工具结果"), t("Budget pressure 在 agent-turn-runtime.ts 中注入 system message"), t("清空上下文设置 cutoff timestamp，不删除数据库记录")],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "model-configuration",
      category: "novelfork-advanced",
      tags: ["模型","供应商","API","fallback","配置"],
      title: t("模型选择与配置"),
      summary: t("选择适合写作的模型、配置供应商、设置 fallback"),
      sections: [
        { title: t("支持的供应商类型"), body: t("| 协议类型 | 说明 | 示例 |\n|----------|------|------|\n| Anthropic 协议 | Claude 系列原生协议 | Anthropic API、AWS Bedrock |\n| OpenAI 协议 | ChatGPT 兼容协议 | OpenAI、DeepSeek、零一万物 |\n| 兼容 API | 任何兼容上述协议的服务 | 本地 Ollama、vLLM、自建代理 |") },
        { title: t("推荐写作模型"), body: t("| 模型 | 优势 | 适用场景 |\n|------|------|----------|\n| Claude Opus 4 | 写作质量最高，理解力强 | 正式写作、复杂剧情 |\n| Claude Sonnet 4 | 平衡质量与速度 | 日常写作、迭代修改 |\n| DeepSeek v4-pro | 性价比高，中文表现好 | 大量写作、预算有限 |") },
        { title: t("如何添加与配置供应商"), body: t("1. 进入 **设置 → AI 供应商**\n2. 点击\"添加供应商\"，选择协议（Anthropic、OpenAI Completions、Responses、Codex Native、Gemini 兼容或 NUG 网关）。\n3. 填写服务信息：\n   - **NUG 服务地址与自动前缀**：输入服务地址时自动推导有意义的域名作为服务名称与前缀（如 `http://nug.example.com` 自动推导 `nug` 前缀）；\n   - **密钥与代理**：配置 API Key 或选择继承代理/自定义代理。\n4. **模型列表与操作**：\n   - 模型列表采用极其紧凑的**单行表格布局**（模型 ID · 显示名 · context window · 操作图标）；\n   - 支持单个与**一键批量“全部隐藏 / 全部显示”**模型；\n   - NUG 反代通道支持查看带可用率百分比进度条的通道健康面板。\n5. **脏检测与保存**：界面修改后底部弹出 Dirty Bar（“有未保存的更改”），确认无误后点击“保存变更”批量写入 Runtime。") },
        { title: t("Model Fallback（自动切备用模型）"), body: t("当主模型不可用时，系统自动尝试下一个供应商：\n\n- **503 / 529（过载）**：等待 → 重试 → 切备用\n- **429（限流）**：按 retry-after 等待 → 重试 → 超时切备用\n- **连接超时**：直接切备用\n- **404（模型不存在）**：报错，不切换\n\n切换时 UI 短暂显示\"已切换到备用模型\"，对话不中断。") },
        { title: t("Reasoning Effort（推理深度）"), body: t("控制模型的思考深度：\n\n| 级别 | 效果 | 适用场景 |\n|------|------|----------|\n| low | 快速回复，少思考 | 简单问答、格式调整 |\n| medium | 平衡 | 日常写作 |\n| high | 深度思考，慢但质量高 | 复杂剧情、架构设计 |\n\n注意：不是所有模型都支持 reasoning effort，不支持时该设置被忽略。") },
        { title: t("Context Window（上下文窗口）"), body: t("不同模型的窗口大小决定了能放多少对话历史：\n\n| 模型 | 窗口大小 | 实际可用（扣除系统提示后） |\n|------|----------|---------------------------|\n| Claude Opus 4 | 200K | ~180K |\n| Claude Sonnet 4 | 200K | ~180K |\n| DeepSeek v4 | 128K | ~115K |\n| GPT-4o | 128K | ~115K |\n\n窗口越大，AI 能记住越多对话内容，压缩频率越低。") },
      ],
      workflow: [],
      bestPractices: [t("**写作用大窗口模型（200K+）**：长篇小说上下文多，避免频繁压缩丢失细节"), t("**配置两个供应商做 fallback**：保证一个挂了另一个顶上，写作不中断"), t("**日常用 medium effort**：high 虽然质量好但慢 2-3 倍，创作流畅度也重要"), t("**检查模型支持的功能**：不是所有模型都支持 tool_use，写作核心流程需要工具支持")],
      pitfalls: [t("**API Key 错误** → 返回 401，检查是否复制完整、有无多余空格"), t("**模型名拼错** → 返回 404，用设置页的\"刷新模型列表\"确认可用模型"), t("**Base URL 多了斜杠** → 连接失败，URL 末尾不要加 `/`"), t("**供应商限流** → 频繁 429，降低并发或换供应商")],
      agentHints: [t("供应商配置存储在 settings store 的 providers 字段"), t("Model fallback 逻辑在 llm/provider.ts 的 chatCompletion 中"), t("Reasoning effort 通过 API 参数 `thinking` 或 `reasoning_effort` 传递"), t("模型列表通过 `/api/providers/:id/models` 端点动态获取")],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "debugging",
      category: "novelfork-advanced",
      tags: ["调试","日志","dump","排错","诊断"],
      title: t("调试与排错"),
      summary: t("遇到问题时如何诊断：日志、Prompt Dump、上下文详情"),
      sections: [
        { title: t("结构化日志格式"), body: t("系统运行时产生结构化 JSON 日志：\n\n```json\n{\"ts\":\"2025-01-15T10:23:45.123Z\",\"level\":\"info\",\"msg\":\"tool executed\",\"fields\":{\"tool\":\"jingwei.read\",\"duration\":234,\"tokens\":1520}}\n```\n\n| 字段 | 说明 |\n|------|------|\n| ts | ISO 时间戳 |\n| level | info / warn / error |\n| msg | 人类可读描述 |\n| fields | 结构化附加数据 |\n\n日志在开发者工具 Console 中可见，生产模式写入文件。") },
        { title: t("如何开启 Prompt Dump"), body: t("Prompt Dump 可以看到 AI **实际收到了什么**——这是排查\"AI 答非所问\"的最有效手段。\n\n1. 进入 **设置 → 开发者选项**\n2. 开启\"Dump API 请求\"\n3. 之后每次 AI 回复都会在 `.narrafork/prompt-dumps/` 生成一个 JSON 文件\n4. 文件内容包含完整的 messages 数组、system prompt、工具定义") },
        { title: t("上下文详情面板"), body: t("点击状态栏的上下文圆环 → \"查看上下文详情\"：\n\n- 当前 token 使用量 / 窗口总量\n- 各部分占比（系统提示、历史消息、工具结果、经纬数据）\n- 最近一次压缩的时间和摘要内容") },
        { title: t("常见问题排查"), body: t("### \"AI 答非所问\"\n\n**原因**：AI 收到的上下文和你以为的不一样。\n\n排查步骤：\n1. 开启 Prompt Dump\n2. 复现问题\n3. 打开 dump 文件，看 messages 数组中实际包含了什么\n4. 常见原因：经纬数据缺失、上下文被压缩丢了关键信息、系统提示被覆盖\n\n### \"上下文百分比不动\"\n\n**原因**：模型没有正确返回 usage 信息。\n\n排查步骤：\n1. 检查供应商是否支持 usage 返回（部分代理会剥离 usage 字段）\n2. 查看 Console 日志中是否有 `usage missing` 警告\n3. 尝试换一个供应商测试\n\n### \"工具卡住不动\"\n\n**原因**：有待确认的权限请求未回答。\n\n排查步骤：\n1. 检查对话区域是否有未回答的确认按钮\n2. 检查是否处于 ask-always 模式且弹窗被遮挡\n3. 查看日志中是否有 `tool_timeout` 错误\n\n### \"网络错误\"\n\n**原因**：供应商 URL 或 API Key 配置问题。\n\n排查步骤：\n1. 设置 → AI 供应商 → 测试连接\n2. 检查 Base URL 格式（不要多加 `/`，不要漏掉 `https://`）\n3. 检查 API Key 是否过期或额度用完\n4. 检查网络代理设置\n\n### \"模型幻觉（编造内容）\"\n\n**原因**：经纬数据不完整，AI 没有足够的设定参考。\n\n排查步骤：\n1. 检查经纬中是否有该角色/地点/事件的条目\n2. 补充缺失的设定数据\n3. 重新生成，观察是否改善") },
        { title: t("Turn Profiler（开发者工具）"), body: t("在开发模式下可用，显示每个 Agent 回合的性能数据：\n\n| 指标 | 说明 |\n|------|------|\n| total_duration | 整个回合耗时 |\n| llm_time | 模型推理耗时 |\n| tool_time | 工具执行耗时 |\n| tokens_in | 输入 token 数 |\n| tokens_out | 输出 token 数 |\n| tool_calls | 工具调用次数 |\n\n在 Console 中搜索 `[turn-profiler]` 可看到每回合的性能摘要。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [t("Prompt Dump 文件路径：`.narrafork/prompt-dumps/{timestamp}-{session-id}.json`"), t("日志级别可在设置中调整（info/debug/warn）"), t("Turn Profiler 仅开发模式启用，生产模式关闭"), t("上下文详情数据来自最近一次 API 响应的 usage 字段"), t("网络错误时检查 error.code 区分超时(TIMEOUT)、拒绝(ECONNREFUSED)、DNS(ENOTFOUND)")],
      actions: [
      { label: t("前往"), description: t("/next/settings"), href: "/next/settings" },
      ],
    },
    {
      id: "platform-writing-cards",
      category: "novelfork-advanced",
      tags: ["平台","发布","章字数","敏感词","AI率","合规","番茄","起点","晋江","七猫"],
      title: t("平台写作卡"),
      summary: t("各连载平台的章字数、钩子密度、AI 率与敏感尺度口径，以及它们如何进入写前预检与发布自检"),
      sections: [
        { title: t("各平台口径"), body: t("### 番茄小说（fanqie）\n\n| 项 | 值 |\n|---|---|\n| 章字数 | 1500 / **2200** / 3500（最少 / 建议 / 最多） |\n| 每章钩子 | 至少 1，建议 2 |\n| AI 率容忍 | 20% |\n| 敏感词阻断 | 是 |\n\n- 快节奏：每章至少一个明确推进与一个新钩子。\n- 章尾留断点，避免平收。\n\n### 起点中文网（qidian）\n\n| 项 | 值 |\n|---|---|\n| 章字数 | 2000 / **3000** / 4500 |\n| 每章钩子 | 至少 1，建议 1 |\n| AI 率容忍 | **0（零容忍口径）** |\n| 敏感词阻断 | 是 |\n\n- 重信息增量与设定自洽，慢热可接受但每章要有增量。\n- AI 味零容忍口径：写后必做去 AI 与人工复核。\n\n### 晋江文学城（jjwxc）\n\n| 项 | 值 |\n|---|---|\n| 章字数 | 2000 / **3000** / 6000 |\n| 每章钩子 | 至少 0，建议 1 |\n| AI 率容忍 | 5% |\n| 敏感词阻断 | 是 |\n\n- 重人物内心与关系推进，情绪线要连贯。\n- 敏感尺度从严，涉及情节需自审。\n\n### 七猫小说（qimao）\n\n| 项 | 值 |\n|---|---|\n| 章字数 | 1500 / **2200** / 3500 |\n| 每章钩子 | 至少 1，建议 2 |\n| AI 率容忍 | 20% |\n| 敏感词阻断 | 是 |\n\n- 与番茄相近的快节奏口径；章尾钩子必备。\n\n### 通用（generic）\n\n| 项 | 值 |\n|---|---|\n| 章字数 | 1500 / **3000** / 6000 |\n| 每章钩子 | 至少 0，建议 1 |\n| AI 率容忍 | 20% |\n| 敏感词阻断 | **否** ") },
        { title: t("平台名怎么写"), body: t("书籍 `platform` 支持中英文别名，大小写不敏感：\n\n| 你填的 | 解析为 |\n|---|---|\n| `tomato` / `fanqie` / `番茄` | 番茄小说 |\n| `qidian` / `起点` | 起点中文网 |\n| `jjwxc` / `晋江` | 晋江文学城 |\n| `qimao` / `七猫` | 七猫小说 |\n| `feilu` / `飞卢` / `other` / 未填 / 无法识别 | 通用 |\n\n飞卢目前没有独立 profile，按通用口径处理。") },
        { title: t("它在哪里生效"), body: t("**写前预检**（`write.preflight`）会带上平台标签，并在书籍章字数目标与平台窗口不符时给 `platform-target-mismatch` 告警。这是提醒，不阻断。\n\n**保存正文时**（`pipeline.write`）做单章轻检，默认只提醒。只有在平台 `blockOnSensitiveBlock=true` 且命中阻断级敏感词时，才会 `publish-blocked` 不保存 —— 这是唯一会因平台口径拦住保存的情况。\n\n**发布自检**（`publish.check`）做四个维度：敏感词、AI 率、格式、连续性，按平台口径给出 ready / has-warnings / blocked。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [t("**把 AI 率容忍当承诺**：`aiRatioTolerance` 是估算口径，不是平台官方阈值。起点写 0 表示\"按零容忍对待\"，不代表存在一个官方 0% 检测。"), t("**靠通用口径投稿具体平台**：没填 `platform` 就拿不到该平台的字数窗口和敏感尺度，发布自检也只做基础检查。"), t("**指望自检替代人工过审**：敏感词与 AI 率都是本地启发式判断，最终以平台实际审核为准。")],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
    {
      id: "writing-sop",
      category: "novelfork-advanced",
      tags: ["SOP","流程","写作","拆书","续写","废稿","发布","写前预检"],
      title: t("写作 SOP"),
      summary: t("开新书、续写旧书、写下一章、废稿重开、发布前自检的标准动作顺序"),
      sections: [
        { title: t("场景一：写下一章（最常用）"), body: t("1. 打开工作台侧栏的 **写作** 视图（✍️）。\n2. 看**就绪条**：\n   - 🟢 绿灯 → 可以写。\n   - 🟡 黄灯 → 可以写，但有提醒，值得先扫一眼。\n   - 🔴 红灯 → **别写**，先处理阻断项。\n3. 展开有问题的检查项，读「发生了什么 / 为什么要看 / 建议怎么做」。能一键修的点「一键修」，它会把请求交给叙述者执行。\n4. 在「第 N 章要发生什么」里写**一句**本章目标（至少 8 字）。这一句决定本章走向，比任何设定都重要。\n   - 留空则采用当前焦点的默认目标，但需要勾选确认。\n5. 点 **生成蓝图** 先看结构，或 **直接写章** 一步到底。\n\n> 也可以在对话里直接说\"写下一章\"。叙述者同样必须先过 `write.preflight`，preflight 不通过它会停下告诉你缺什么。") },
        { title: t("场景二：续写一本已有的旧书"), body: t("1. 命令面板（Ctrl+Shift+P）→ **导入旧书 / 拆书**。\n2. 提供文本或文件，叙述者用 `pipeline.import_chapters` 导入（默认同时结算记忆并抽取简要设定）。\n3. 拆书产物一律落在 **待确认（needs-review）**，不会直接变成 canon。\n4. 去经纬工作区「设定」分区逐条过：对的留下并升为 canon，有幻觉的直接改或删。\n5. 回写作视图跑一次预检，确认近章记忆已就位。\n6. 按场景一开写。\n\n**别跳第 4 步。** 机器抽取一定有噪声，把它当 canon 会污染后续所有章节。") },
        { title: t("场景三：预检报\"近章记忆为空\""), body: t("说明有正文但没结算过记忆，写手会自行编造前情。先判断这些章是什么：\n\n- **是正史，要继续用** → 点「一键修」，或让叙述者 `memory.settle_range` 回填。\n- **是废稿，不要了** → 走场景四，**不要**给废稿养正史。") },
        { title: t("场景四：试写了几章，写废了要重开"), body: t("1. 让叙述者 `chapter.discard_range` 作废该范围（必须 `confirm=true`）。\n2. 它会归档正文、清掉范围内的事件与事实、按策略重置伏笔；**不动**经纬里的静态设定。\n3. 再跑 `write.preflight`，确认近章记忆已干净。\n4. 从场景一重新开写。") },
        { title: t("场景五：中盘防跑偏"), body: t("- **卷纲**：`outline.volume(action=get)` 看当前卷目标；没有就 `suggest` 生成草案，你确认后再 `set`。当前卷目标会自动进入预检和蓝图。\n- **角色弧**：`arc.character` 查谁的成长线停滞或回退了。\n- **伏笔**：预检会报 `hooks-overdue`；伏笔看板在「工具」视图。") },
        { title: t("场景六：发布前"), body: t("1. `publish.check` 做平台自检：敏感词、AI 率、格式、连续性。\n2. 按结果处理：\n   - **ready** → 可发。\n   - **has-warnings** → 能发，但先看提醒。\n   - **blocked** → 有阻断级问题，处理完再发。\n3. 平台口径见[平台写作卡](./26-platform-writing-cards.md)。\n\n> `pipeline.write` 保存前已做单章轻检，默认只提醒。只有平台要求且命中阻断级敏感词时才会拒绝保存。") },
      ],
      workflow: [],
      bestPractices: [],
      pitfalls: [],
      agentHints: [],
      actions: [
      { label: t("前往"), description: t("/next/books/:bookId"), href: "/next/books/:bookId" },
      ],
    },
  ],
};
