/**
 * Novel-domain session tool definitions.
 *
 * Architecture: inputSchema definitions live in packages/novel-plugin/src/tool-schemas.ts
 * (the single source of truth). This file adds session-specific metadata (risk, renderer,
 * enabledForModes, visibility) that only the studio runtime needs.
 */
import { NOVEL_TOOL_SCHEMAS } from "../tool-schemas.js";
import type { ToolInputSchema } from "../tool-schemas.js";
import type {
  JsonObjectSchema,
  SessionToolDefinition,
} from "@vivy1024/novelfork-studio/shared/agent-native-workspace";
import type { SessionPermissionMode } from "@vivy1024/novelfork-studio/shared/session-types";

const ALL_SESSION_PERMISSION_MODES: readonly SessionPermissionMode[] = ["ask", "edit", "allow", "read", "plan"];
const WRITE_SESSION_PERMISSION_MODES: readonly SessionPermissionMode[] = ["ask", "edit", "allow"];

/** Convert ToolInputSchema from novel-plugin to JsonObjectSchema used by session tools */
function toJsonObjectSchema(schema: ToolInputSchema): JsonObjectSchema {
  return schema as unknown as JsonObjectSchema;
}

function sessionTool(
  definition: Omit<SessionToolDefinition, "visibility"> & Partial<Pick<SessionToolDefinition, "visibility">>,
): SessionToolDefinition {
  return { visibility: "author", ...definition };
}

/**
 * 小说领域工具定义 — session-level metadata wrapping novel-plugin schemas
 */
export const NOVEL_SESSION_TOOL_DEFINITIONS: readonly SessionToolDefinition[] = [
  sessionTool({
    name: "cockpit.snapshot",
    description:
      "一次性读取当前书籍的驾驶舱全景快照，合并了 cockpit.get_snapshot、cockpit.list_open_hooks、cockpit.list_recent_candidates 的输出。返回 progress/hooks/candidates/health/recentChapters。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["cockpit.snapshot"]),
    risk: "read",
    renderer: "cockpit.snapshot",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "cockpit.get_snapshot",
    description: "读取当前书籍的驾驶舱快照，包括进度、当前焦点、风险、伏笔、候选稿与模型状态。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["cockpit.get_snapshot"]),
    risk: "read",
    renderer: "cockpit.snapshot",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "cockpit.list_open_hooks",
    description: "列出当前书籍仍待推进或回收的伏笔与开放 hook。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["cockpit.list_open_hooks"]),
    risk: "read",
    renderer: "cockpit.openHooks",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "cockpit.list_recent_candidates",
    description: "列出当前书籍最近生成的候选稿与可在画布打开的 artifact 引用。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["cockpit.list_recent_candidates"]),
    risk: "read",
    renderer: "cockpit.recentCandidates",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "questionnaire.list_templates",
    description: "列出可用于建立书籍前提、世界模型、人物弧光或主要矛盾的问卷模板。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["questionnaire.list_templates"]),
    risk: "read",
    renderer: "questionnaire.templates",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "questionnaire.start",
    description: "根据模板启动结构化问卷流程，返回待展示的问题卡，不写入正式经纬。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["questionnaire.start"]),
    risk: "read",
    renderer: "questionnaire.questions",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "questionnaire.suggest_answer",
    description: "基于真实 provider/model 上下文为问卷问题生成建议答案；模型不可用时应返回 unsupported。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["questionnaire.suggest_answer"]),
    risk: "read",
    renderer: "questionnaire.suggestion",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "questionnaire.submit_response",
    description: "提交问卷回答并准备写入 Bible/Jingwei 的事务化 mapping；正式写入必须经过确认。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["questionnaire.submit_response"]),
    risk: "confirmed-write",
    renderer: "jingwei.mutationPreview",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pgi.ask",
    description: "PGI 追问工具（三合一）：生成追问问题 + 返回 AskUserQuestion 格式 + 格式化用户回答为写作指示。替代旧的 pgi.generate_questions/record_answers/format_answers_for_prompt。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pgi.ask"]),
    risk: "read",
    renderer: "pgi.ask",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pgi.generate_questions",
    description: "根据当前章节意图、伏笔、冲突与章节上下文生成 2-5 个生成前追问。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pgi.generate_questions"]),
    risk: "read",
    renderer: "pgi.questions",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pgi.record_answers",
    description: "记录 PGI 问题回答或跳过原因，用作后续候选稿 metadata 与写作上下文。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pgi.record_answers"]),
    risk: "draft-write",
    renderer: "pgi.answers",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pgi.format_answers_for_prompt",
    description: "将 PGI 问题与答案整理成 writer 可直接使用的本章作者指示。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pgi.format_answers_for_prompt"]),
    risk: "read",
    renderer: "pgi.promptInstructions",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "guided.enter",
    description: "进入引导式生成模式，生成待用户回答/确认的问题卡，不直接写入正式内容。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["guided.enter"]),
    risk: "read",
    renderer: "guided.questions",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "guided.answer_question",
    description: "记录引导式生成问题回答或跳过项，更新引导状态但不写入正式正文。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["guided.answer_question"]),
    risk: "draft-write",
    renderer: "guided.questions",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "guided.exit",
    description: "提交引导式生成计划；需要确认后进入执行阶段。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["guided.exit"]),
    risk: "confirmed-write",
    renderer: "guided.plan",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "candidate.create_chapter",
    description: "仅保存已有章节正文为候选稿。不会生成正文、不会审计、不会修订、不会同步经纬；完整写下一章必须优先调用 pipeline.generate_chapter。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["candidate.create_chapter"]),
    risk: "draft-write",
    renderer: "candidate.created",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "narrative.read_line",
    description: "读取当前书籍的叙事线只读快照，包括节点、边与可计算 warnings。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["narrative.read_line"]),
    risk: "read",
    renderer: "narrative.line",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "narrative.propose_change",
    description: "生成叙事线变更草案和差异预览，不直接写入正式叙事线。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["narrative.propose_change"]),
    risk: "draft-write",
    renderer: "narrative.mutationPreview",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  // --- 小说上下文工具组 (Task 23) ---
  sessionTool({
    name: "chapter.read",
    description: "读取指定章节的正文内容、元数据和状态。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["chapter.read"]),
    risk: "read",
    renderer: "chapter.content",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "chapter.list",
    description: "列出书籍的所有章节（序号、标题、字数、状态）。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["chapter.list"]),
    risk: "read",
    renderer: "chapter.list",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.read_brief",
    description: "读取小型经纬核心包和分类目录，作为写作/审计任务的默认第一步。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.read_brief"]),
    risk: "read",
    renderer: "jingwei.brief",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.read_category",
    description: "按分类、分页和预算读取经纬条目细节，避免一次性全量注入。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.read_category"]),
    risk: "read",
    renderer: "jingwei.category",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.search",
    description: "按关键词、别名、标签和正文搜索经纬条目，用于缺信息时精准补读。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.search"]),
    risk: "read",
    renderer: "jingwei.search",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.read_context",
    description: "兼容读取书籍故事经纬上下文；新流程请优先使用 jingwei.read_brief + jingwei.read_category，full 不再代表无界全量读取。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.read_context"]),
    risk: "read",
    renderer: "jingwei.context",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "health.read_summary",
    description: "读取作品健康度摘要，包括进度、风险、缺口和下一步建议。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["health.read_summary"]),
    risk: "read",
    renderer: "health.summary",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  // --- 新增小说工具组 (5 tools) ---
  sessionTool({
    name: "chapter.audit",
    description: "对单章执行质量审计，包括节奏分析、AI 味检测、伏笔到期检查、连续性检查。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["chapter.audit"]),
    risk: "read",
    renderer: "chapter.audit",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "rewrite.segment",
    description: "对章节中选定段落执行改写（续写/扩写/去AI味/风格改写），调用 LLM 生成改写结果。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["rewrite.segment"]),
    risk: "read",
    renderer: "tool.rewrite-segment",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "style.import",
    description: "从参考文本提取文风档案（统计分析+LLM 定性描述），生成 style_profile.json 和 style_guide.md。参考文本至少 2000 字。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["style.import"]),
    risk: "draft-write",
    renderer: "style.import",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pipeline.revise",
    description: "修订已有章节。支持 5 种模式：polish（润色）、rewrite（重写）、rework（大改）、spot-fix（定点修复）、anti-detect（去AI味）。不填章节号则修订最新章。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pipeline.revise"]),
    risk: "draft-write",
    renderer: "pipeline.revise",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pipeline.import_chapters",
    description: "整书导入工具。从 .txt/.md 文件中按章节标题分割并导入所有章节到指定书籍。自动生成文风统计。文件路径需为服务器本地路径。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pipeline.import_chapters"]),
    risk: "draft-write",
    renderer: "pipeline.import_chapters",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "outline.suggest_next",
    description: "基于大纲、最近章节和待兑现伏笔，推荐下一章的 2-3 个写作方向。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["outline.suggest_next"]),
    risk: "read",
    renderer: "outline.suggestions",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "character.check_consistency",
    description: "检查角色在指定章节范围内的出现频率和上下文，辅助人设一致性审查。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["character.check_consistency"]),
    risk: "read",
    renderer: "character.consistency",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "hooks.manage",
    description: "伏笔统一管理：埋设、兑现、检查到期、列出所有伏笔。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["hooks.manage"]),
    risk: "draft-write",
    renderer: "hooks.manage",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  // --- 预设与节拍工具 (cockpit-redesign spec) ---
  // v2 合并工具：presets.read/write、beat.read/write（旧工具名保留兼容，但默认隐藏）
  sessionTool({
    name: "presets.read",
    description: "读取预设。scope=enabled（默认）返回当前书籍已启用规则（含 promptInjection 全文）；scope=available 返回全部可用预设（含启用标记，可按 category 过滤）。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.read"]),
    risk: "read",
    renderer: "presets.rules",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "presets.write",
    description: "写预设。action=enable/disable/set 改变书籍启用的预设列表（传 enabledPresetIds）；action=create 创建自定义预设（传 name/category/promptInjection）。promptInjection 是注入写作 prompt 的规则全文。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.write"]),
    risk: "confirmed-write",
    renderer: "presets.rules",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "beat.read",
    description: "读取当前书籍的节拍模板与节拍列表，返回模板名、节拍序号、名称、情绪基调、字数建议；未选中模板时返回可选模板列表。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["beat.read"]),
    risk: "read",
    renderer: "beat.current",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "beat.write",
    description: "写节拍。action=select 切换到已有模板（传 templateId，可用：opening-hooks/three-act/save-the-cat/heros-journey/chapter-ending-hooks）；action=create 创建自定义节拍（传 name/description/beats）。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["beat.write"]),
    risk: "confirmed-write",
    renderer: "beat.current",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "presets.get_rules",
    description: "读取当前书籍启用的预设规则列表，返回每条预设的名称、分类和 promptInjection。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.get_rules"]),
    risk: "read",
    renderer: "presets.rules",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "presets.check_compliance",
    description: "对照启用的预设规则逐条检查章节内容，返回违规项列表。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.check_compliance"]),
    risk: "read",
    renderer: "presets.compliance",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "beat.get_current",
    description: "读取当前书籍的节拍模板与节拍列表，返回模板名、节拍序号、名称、情绪基调、字数建议。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["beat.get_current"]),
    risk: "read",
    renderer: "beat.current",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "beat.set_template",
    description: "为当前书籍设置节拍模板。可用模板：opening-hooks（网文开篇钩子12式）、three-act（三幕结构）、save-the-cat（救猫咪15节拍）、heros-journey（英雄之旅17阶段）、chapter-ending-hooks（章节结尾钩子生成器）。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["beat.set_template"]),
    risk: "confirmed-write",
    renderer: "beat.current",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "presets.set_rules",
    description: "为当前书籍设置启用的预设规则列表。传空数组清空所有预设。可通过 presets.get_rules 查看当前启用的预设，通过 /api/presets 查看所有可用预设。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.set_rules"]),
    risk: "confirmed-write",
    renderer: "presets.rules",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "presets.create_custom",
    description: "创建自定义预设规则。promptInjection 是注入写作 prompt 的规则文本，是预设的核心。创建后需要用 presets.set_rules 将其 ID 加入启用列表才会生效。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.create_custom"]),
    risk: "confirmed-write",
    renderer: "presets.rules",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "presets.list_available",
    description: "列出所有可用预设（内置+自定义），可按分类筛选，传入 bookId 时标注哪些已启用。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["presets.list_available"]),
    risk: "read",
    renderer: "presets.list",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "beat.create_custom",
    description: "创建自定义节拍模板。定义自己的节拍序列（名称、情绪、字数占比、目的）。创建后用 beat.set_template 设置为当前书籍的节拍模板。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["beat.create_custom"]),
    risk: "confirmed-write",
    renderer: "beat.current",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pipeline.write",
    description: "精简写作管线（v2）：接受 scene.spec 生成的结构化蓝图，执行 Writer→AuditRevise 两步生成章节候选稿。前置条件：必须先调用 scene.spec 获得有效蓝图。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pipeline.write"]),
    risk: "draft-write",
    renderer: "pipeline.chapter-result",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "pipeline.generate_chapter",
    description: "完整写作管线：规划→上下文组装→正文生成→审计→修订→经纬同步→保存候选稿。写下一章时应优先调用本工具；非整章任务（写一段、改一句）请直接输出。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["pipeline.generate_chapter"]),
    risk: "draft-write",
    renderer: "pipeline.chapter-result",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.upsert_entry",
    description: "创建或更新经纬条目。按 title 匹配：标题相同则更新内容，不存在则创建。类别不存在时自动创建。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.upsert_entry"]),
    risk: "confirmed-write",
    renderer: "jingwei.upsert",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.write",
    description: "经纬写入/删除工具。action=create/update 创建或更新条目；action=delete 删除条目（Canon 条目不可删除）。支持 layer 分层：canon（不可变）、dynamic（默认）、reference。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.write"]),
    risk: "draft-write",
    renderer: "jingwei.write",
    enabledForModes: WRITE_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "scene.spec",
    description: "生成结构化写作蓝图（Scene Spec）。包含角色、地点、冲突、情绪、结果等约束，是调用 pipeline.write 的硬前置条件。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["scene.spec"]),
    risk: "read",
    renderer: "scene.spec",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
  sessionTool({
    name: "jingwei.read",
    description: "统一经纬读取工具。scope=brief 返回核心包+分类目录；scope=category 按分类分页读取；scope=search 按关键词搜索。替代旧的 read_brief/read_category/search/read_context。",
    inputSchema: toJsonObjectSchema(NOVEL_TOOL_SCHEMAS["jingwei.read"]),
    risk: "read",
    renderer: "jingwei.read",
    enabledForModes: ALL_SESSION_PERMISSION_MODES,
    scope: "novel",
  }),
] as const;

/**
 * 小说工具名列表 — 供 novel-plugin manifest 引用
 */
export const NOVEL_TOOL_NAMES: readonly string[] = NOVEL_SESSION_TOOL_DEFINITIONS.map((t) => t.name);

/**
 * 小说 Agent 角色预设 — 与 AGENT_ROLES 保持一致
 */
export const NOVEL_AGENT_PRESETS: Record<string, { enable: string[]; disable: string[] }> = {
  writer: {
    enable: ["Bash", "Read", "Write", "Edit", "Grep", "Glob", "EnterWorktree", "ExitWorktree", "TaskCreate"],
    disable: ["Terminal", "Browser", "ForkNarrator", "Recall", "ShareFile"],
  },
  planner: {
    enable: ["Read", "Write", "Edit", "Grep", "Glob"],
    disable: ["Bash", "Terminal", "Browser", "ForkNarrator"],
  },
  auditor: {
    enable: ["Read", "Grep", "Glob"],
    disable: ["Write", "Edit", "Bash", "Terminal", "Browser", "ForkNarrator"],
  },
  architect: {
    enable: ["Read", "Write", "Edit", "Grep", "Glob"],
    disable: ["Bash", "Terminal", "Browser", "ForkNarrator"],
  },
  explorer: {
    enable: ["Read", "Grep", "Glob", "Recall"],
    disable: ["Write", "Edit", "Bash", "Terminal", "Browser", "ForkNarrator", "ShareFile"],
  },
  hooks: {
    enable: ["Read", "Write", "Grep", "Glob"],
    disable: ["Bash", "Terminal", "Browser", "ForkNarrator"],
  },
  "chapter-hooks": {
    enable: ["Read", "Grep", "Glob"],
    disable: ["Write", "Edit", "Bash", "Terminal", "Browser"],
  },
  outline: {
    enable: ["Read", "Write", "Edit", "Grep", "Glob"],
    disable: ["Bash", "Terminal", "Browser", "ForkNarrator"],
  },
};
