import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface PreparedProductMigrationData {
	readonly generatedFile: string;
	readonly migrationCount: number;
}

type ProductMigrationFile = {
	readonly name: string;
	readonly content: string;
};

function fail(message: string): never {
	throw new Error(`Product release artifact preparation failed: ${message}`);
}

function assertDirectory(path: string, label: string): void {
	if (!existsSync(path) || !statSync(path).isDirectory()) {
		fail(`${label} is missing: ${path}`);
	}
}

/**
 * Writes compiled-only product migration data into the disposable workspace.
 * The checked-in source placeholder remains empty so normal source execution
 * continues to read the SQL files directly from disk.
 */
export function prepareEmbeddedProductMigrationData(workspaceRoot: string): PreparedProductMigrationData {
	const databaseRoot = join(
		workspaceRoot,
		"packages",
		"novelfork-product-runtime",
		"src",
		"db",
	);
	const migrationsRoot = join(databaseRoot, "migrations");
	const generatedFile = join(databaseRoot, "generated-migrations-data.ts");
	assertDirectory(migrationsRoot, "NovelFork product migrations directory");

	const files = readdirSync(migrationsRoot, { withFileTypes: true })
		.filter((entry) => entry.isFile() && /^\d+.*\.sql$/u.test(entry.name))
		.map((entry) => entry.name)
		.sort((left, right) => left.localeCompare(right));
	if (files.length === 0) {
		fail(`NovelFork product migrations directory is empty: ${migrationsRoot}`);
	}

	const migrations: readonly ProductMigrationFile[] = files.map((name) => ({
		name,
		content: readFileSync(join(migrationsRoot, name), "utf8"),
	}));
	mkdirSync(databaseRoot, { recursive: true });
	writeFileSync(
		generatedFile,
		`// AUTO-GENERATED by scripts/compile-product-runtime.ts — DO NOT EDIT\nexport const embeddedProductMigrationSqlFiles: ReadonlyArray<{ readonly name: string; readonly content: string }> = ${JSON.stringify(migrations, null, "\t")};\n`,
	);

	return { generatedFile, migrationCount: migrations.length };
}
