import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

export const REQUIRED_PARCEL_WATCHER_PLATFORMS = [
	"darwin-arm64",
	"darwin-x64",
	"linux-x64-glibc",
	"linux-x64-musl",
	"linux-arm64-glibc",
	"linux-arm64-musl",
	"win32-x64",
	"win32-arm64",
] as const;

export interface RuntimeReleaseArtifactOptions {
	readonly runtimeRoot: string;
	readonly productName: string;
	readonly productVersion: string;
	readonly buildCommit: string;
	readonly buildPlatform: string;
	/** Controlled child-process environment for Runtime generators. */
	readonly environment?: NodeJS.ProcessEnv;
}

export interface RuntimeReleaseArtifactHooks {
	readonly generateParcelWatcher?: (runtimeRoot: string) => void;
	/** Test seam for observing the controlled Runtime generator environment. */
	readonly runBun?: (
		runtimeRoot: string,
		args: readonly string[],
		purpose: string,
		environment: NodeJS.ProcessEnv,
	) => void;
}

export interface PreparedRuntimeReleaseArtifacts {
	readonly generatedFiles: readonly string[];
	readonly frontendAssetCount: number;
	readonly migrationCount: number;
	readonly changelogCount: number;
}

type DrizzleJournal = {
	entries: Array<{ tag: string }>;
};

type ChangelogEntry = {
	version: string;
	date: string;
	en: string;
	readonly [locale: string]: string;
};

function fail(message: string): never {
	throw new Error(`Runtime release artifact preparation failed: ${message}`);
}

function assertFile(path: string, label: string): void {
	if (!existsSync(path) || !statSync(path).isFile()) {
		fail(`${label} is missing: ${path}`);
	}
}

function runBun(
	runtimeRoot: string,
	args: readonly string[],
	purpose: string,
	environment: NodeJS.ProcessEnv,
): void {
	const child = Bun.spawnSync([process.execPath, ...args], {
		cwd: runtimeRoot,
		env: environment,
		stdio: ["inherit", "inherit", "inherit"],
	});
	if (child.exitCode !== 0) {
		fail(`${purpose} exited with code ${child.exitCode ?? "unknown"}`);
	}
}

function walkRegularFiles(root: string): string[] {
	if (!existsSync(root)) fail(`directory is missing: ${root}`);

	const files: string[] = [];
	const visit = (directory: string): void => {
		const entries = readdirSync(directory, { withFileTypes: true }).sort((left, right) =>
			left.name.localeCompare(right.name),
		);
		for (const entry of entries) {
			const entryPath = join(directory, entry.name);
			if (entry.isDirectory()) {
				visit(entryPath);
				continue;
			}
			if (!entry.isFile()) {
				fail(`release assets must be regular files: ${entryPath}`);
			}
			files.push(entryPath);
		}
	};

	visit(root);
	return files;
}

function importSpecifier(fromFile: string, toFile: string): string {
	const value = relative(dirname(fromFile), toFile).replaceAll(sep, "/");
	return value.startsWith(".") ? value : `./${value}`;
}

function generateEmbeddedFrontend(runtimeRoot: string): { path: string; count: number } {
	const frontendRoot = join(runtimeRoot, "dist", "frontend");
	const output = join(runtimeRoot, "server", "generated", "embedded-frontend.ts");
	const assets = walkRegularFiles(frontendRoot);
	if (assets.length === 0) fail(`frontend build contains no files: ${frontendRoot}`);

	const imports: string[] = [];
	const entries: string[] = [];
	for (const [index, asset] of assets.entries()) {
		const urlPath = `/${relative(frontendRoot, asset).replaceAll(sep, "/")}`;
		imports.push(
			`import _asset${index} from ${JSON.stringify(importSpecifier(output, asset))} with { type: "file" };`,
		);
		entries.push(`\t${JSON.stringify(urlPath)}: _asset${index},`);
	}

	writeFileSync(
		output,
		`// AUTO-GENERATED by scripts/compile-product-runtime.ts — DO NOT EDIT\n${imports.join("\n")}\n\n/** URL path → embedded file path (resolved at compile time via $bunfs) */\nexport const embeddedAssets: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
	);
	return { path: output, count: assets.length };
}

function generateEmbeddedMigrations(runtimeRoot: string): { path: string; count: number } {
	const drizzleRoot = join(runtimeRoot, "drizzle");
	const journalPath = join(drizzleRoot, "meta", "_journal.json");
	const output = join(runtimeRoot, "server", "generated", "embedded-migrations-data.ts");
	assertFile(journalPath, "Drizzle migration journal");

	const journalJson = readFileSync(journalPath, "utf8");
	let journal: DrizzleJournal;
	try {
		journal = JSON.parse(journalJson) as DrizzleJournal;
	} catch (error) {
		fail(`Drizzle migration journal is invalid JSON (${String(error)})`);
	}
	if (!Array.isArray(journal.entries)) {
		fail(`Drizzle migration journal has no entries array: ${journalPath}`);
	}

	const files = journal.entries.map((entry) => {
		if (!entry || typeof entry.tag !== "string" || entry.tag.length === 0) {
			fail(`Drizzle migration journal contains an invalid tag: ${JSON.stringify(entry)}`);
		}
		const name = `${entry.tag}.sql`;
		const path = join(drizzleRoot, name);
		assertFile(path, "Drizzle migration SQL");
		return { name, content: readFileSync(path, "utf8") };
	});

	const entries = files
		.map(
			(file) =>
				`\t{ name: ${JSON.stringify(file.name)}, content: ${JSON.stringify(file.content)} },`,
		)
		.join("\n");
	writeFileSync(
		output,
		`// AUTO-GENERATED by scripts/compile-product-runtime.ts — DO NOT EDIT\nexport const embeddedMigrationJournalJson = ${JSON.stringify(journalJson)};\n\nexport const embeddedMigrationSqlFiles: ReadonlyArray<{ name: string; content: string }> = [\n${entries}\n];\n`,
	);
	return { path: output, count: files.length };
}

function parseSemver(value: string): [number, number, number] | undefined {
	const match = value.match(/^v?(\d+)\.(\d+)\.(\d+)(?:[-+][0-9A-Za-z.-]+)?$/);
	if (!match) return undefined;
	const parsed = match.slice(1, 4).map(Number);
	return parsed.every(Number.isSafeInteger)
		? (parsed as [number, number, number])
		: undefined;
}

function compareChangelogsDesc(left: ChangelogEntry, right: ChangelogEntry): number {
	const leftVersion = parseSemver(left.version);
	const rightVersion = parseSemver(right.version);
	if (!leftVersion || !rightVersion) return right.version.localeCompare(left.version);
	for (let index = 0; index < 3; index += 1) {
		const difference = rightVersion[index] - leftVersion[index];
		if (difference !== 0) return difference;
	}
	return right.version.localeCompare(left.version);
}

function generateEmbeddedChangelog(runtimeRoot: string): { path: string; count: number } {
	const changelogRoot = join(runtimeRoot, "changelogs");
	const output = join(runtimeRoot, "server", "generated", "embedded-changelog.ts");
	const entries: ChangelogEntry[] = [];

	if (existsSync(changelogRoot)) {
		for (const path of walkRegularFiles(changelogRoot)) {
			if (!path.endsWith(".json")) continue;
			try {
				const candidate = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
				if (
					typeof candidate.version !== "string" ||
					typeof candidate.date !== "string" ||
					typeof candidate.en !== "string" ||
					!parseSemver(candidate.version)
				) {
					continue;
				}
				const values = Object.entries(candidate);
				if (values.some(([, value]) => typeof value !== "string")) continue;
				entries.push(candidate as ChangelogEntry);
			} catch {
				// A malformed changelog must not make its way into a release binary.
			}
		}
	}

	entries.sort(compareChangelogsDesc);
	writeFileSync(
		output,
		`// AUTO-GENERATED by scripts/compile-product-runtime.ts — DO NOT EDIT\nexport const embeddedChangelogs = ${JSON.stringify(entries, null, "\t")} as const;\n`,
	);
	return { path: output, count: entries.length };
}

/**
 * Rewrite only the per-platform build metadata. Cross-platform releases share
 * every other generated artifact, so a multi-platform compile prepares the
 * heavy artifacts once and calls this per target.
 */
export function writeRuntimeBuildInfo(
	runtimeRoot: string,
	options: RuntimeReleaseArtifactOptions,
): string {
	const generatedRoot = join(runtimeRoot, "server", "generated");
	mkdirSync(generatedRoot, { recursive: true });
	const output = join(generatedRoot, "build-info.ts");
	writeFileSync(
		output,
		`// AUTO-GENERATED by scripts/compile-product-runtime.ts — DO NOT EDIT\nexport const buildProduct = ${JSON.stringify(options.productName)};\nexport const buildVersion = ${JSON.stringify(options.productVersion)};\nexport const buildCommit = ${JSON.stringify(options.buildCommit)};\nexport const buildPlatform = ${JSON.stringify(options.buildPlatform)};\n`,
	);
	return output;
}

function verifyParcelWatcherArtifacts(runtimeRoot: string): void {
	const generatedRoot = join(runtimeRoot, "server", "generated");
	const loader = join(generatedRoot, "parcel-native-loader.ts");
	assertFile(loader, "Parcel watcher native loader");
	const loaderSource = readFileSync(loader, "utf8");
	for (const platform of REQUIRED_PARCEL_WATCHER_PLATFORMS) {
		const binary = join(generatedRoot, "parcel-watcher-binaries", `watcher-${platform}.node`);
		assertFile(binary, `Parcel watcher binary (${platform})`);
		if (!loaderSource.includes(`watcher-${platform}.node`)) {
			fail(`Parcel watcher loader does not embed ${platform}`);
		}
	}
}

/**
 * Materialize every generated file that the generic Runtime needs before Bun
 * compiles NovelFork's root entry. This deliberately writes only ignored
 * generated output inside the Runtime; product behavior remains outside it.
 */
export function prepareRuntimeReleaseArtifacts(
	options: RuntimeReleaseArtifactOptions,
	hooks: RuntimeReleaseArtifactHooks = {},
): PreparedRuntimeReleaseArtifacts {
	const generatedRoot = join(options.runtimeRoot, "server", "generated");
	const environment = options.environment ?? process.env;
	mkdirSync(generatedRoot, { recursive: true });

	if (hooks.generateParcelWatcher) {
		hooks.generateParcelWatcher(options.runtimeRoot);
	} else {
		if (hooks.runBun) {
			hooks.runBun(
				options.runtimeRoot,
				["scripts/download-parcel-watcher.ts"],
				"Parcel watcher generation",
				environment,
			);
		} else {
			runBun(
				options.runtimeRoot,
				["scripts/download-parcel-watcher.ts"],
				"Parcel watcher generation",
				environment,
			);
		}
	}
	verifyParcelWatcherArtifacts(options.runtimeRoot);

	// The isolated Runtime build seeds the verified, checked-in migration journal
	// before this function runs. Do not invoke drizzle-kit here: schema-diff
	// prompts are interactive and a release build must embed an auditable,
	// deterministic migration history rather than silently generating a new base
	// migration against an arbitrary snapshot.
	const frontend = generateEmbeddedFrontend(options.runtimeRoot);
	const migrations = generateEmbeddedMigrations(options.runtimeRoot);
	const changelog = generateEmbeddedChangelog(options.runtimeRoot);
	const buildInfo = writeRuntimeBuildInfo(options.runtimeRoot, options);
	const generatedFiles = [frontend.path, migrations.path, changelog.path, buildInfo];
	for (const path of generatedFiles) assertFile(path, "Generated Runtime release artifact");

	return {
		generatedFiles,
		frontendAssetCount: frontend.count,
		migrationCount: migrations.count,
		changelogCount: changelog.count,
	};
}
